### ISSUE TITLE
Allow components to query the internal state of widgets

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#115]

**Comment by paf31** [comment]
@jdegoes @puffnfresh Here is my proposed API. I think it's easiest to break it into producer and consumer parts. The consumer is the part of the app making the requests for widget state, and the producer is the part of the application which answers the queries.

Please let me know what you think.

## Consumer

For the consumer, I suggest we modify the `Event` monad to support queries. I've prototyped the following API:

We can capture the syntax of the consumer-side in two classes:

```purescript
class (Monad m) <= MonadYield i m where
  yield :: i -> m Unit

class (Monad m) <= MonadQuery f m where
  query :: forall a. f a -> m a
```

We can emit events of type `i`. We also have a typed query language given by the functor `f`. An example is

```purescript
data AceQuery a = GetTextContent (String -> a)
```

The `Event` monad becomes the `EventT i f` monad transformer, which is the free implementation of these operations:

```purescript
data EventM i f a = Yield i a | Query (f a)

newtype EventT i f m a = EventT (m (Either a (EventM i f (EventT i f m a))))
```

We can run `EventT` using

```purescript
runEvent :: forall i f m a. (Monad m) => (i -> m Unit) -> (forall r. f r -> m r) -> EventT i f m a -> m a
```

`EventT` implements `Monad`, `MonadTrans`, `MonadYield` and `MonadQuery`. The `MonadYield` and `MonadQuery` classes allow us to write code generic handlers like we do now with `Alternative` in the `Forms` module, but in practice, we will use `EventT f m (Aff eff)`. For most applications, we will have `f ~ Const Void` (the query language with no queries).

We have

```purescript
yield :: forall i f m. (Functor f, Monad m) => i -> EventT i f m Unit

query :: forall i f m a. (Functor f, Monad m) => f a -> EventT i f m a
```

so we can emit inputs as usual, or write queries like

```purescript
getTextContent :: AceQuery String
getTextContent = GetTextContent id

myHandler :: EventT input AceQuery m _
myHandler = do
  -- Get the Ace editor content
  s <- getTextContent
  -- Emit an event based on the content
  yield $ WordCountChanged (length s)
```

Whatever we decide to do on the producer side, we have a nice declarative specification for event handlers.

We need to modify the type of `Component` and some functions, since the kind of `Event` has changed.

## Producer

The producer side is more interesting, and I think we have a few options. So far we only have a specification - we can choose to implement `MonadQuery` in different ways.

The job of the producer is to take queries and to run them and return a result, so writing a producer generally involves writing a function of type `f a -> m a` where `f` describes the terms of the query language, and `m` is some `Monad` (probably `Eff` or `Aff`).

### Option 1 - Implement queries at the top level

This is probably the path of least resistance, but not very composable. For small numbers of widgets, it might be ok.

Basically, we write a function of type `forall a. f a -> Eff eff a` which implements our query language, and modify `runUIWith` to pass that function to `runEvent` during rendering.

This is a bit like the approach to post render hooks, in that all introspection takes place in one point, effectfully.

### Option 2 - Each component implements its own query language

This would involve adding a function `forall a. f a -> m a` to `Component m res req`. That is, each component implements its own query language.

This would require us to find a way to compose different types of query AST. I haven't figured that out yet.

This would be better in terms of composability if we could make it work.

### Option 3 - Modify `SF`

This is a bit more drastic, and involves changing SF to something like

```purescript
data SF m f i o = SF (i -> SF1 f i o) (forall a. f a -> m a)
```

The advantage would be that pure components could implement query languages too, and the query implementation could have access to the internal state of the signal function.

This seems a bit like overkill, and I don't think it's worth the price of complicating `SF` so much.

## Conclusion

The consumer side is pretty straightforward since it's just the spec, essentially. I couldn't make queries work in `Event` using `ListT`, so there was a separate reason to move to `FreeT`, but I think it works nicely - `EventT` is just `FreeT f` with a yield operation added, so we can think of `yield` as a special query on a component which requests a repaint and returns no result.

I think we should consider implementing option 1, which should be quick, and then reevaluate whether it's worth implementing option 2 or 3.

**Comment by garyb** [comment]
Option 2 - composing query ASTs, could we use the `inject` approach here? That was the original rationale for it: https://github.com/purescript/purescript-free/blob/master/examples/TeletypeCoproduct.purs

**Comment by jdegoes** [comment]
I'll think about this more and respond tomorrow, currently liking 3 the most of the options since I feel there should be no expressive distinction between pure vs. foreign components; but still need to think through all these pieces and make sure they solve our problems. Agreed with @garyb on coproduct solution for 2 or 3.

**Comment by puffnfresh** [comment]
I don't really understand how bundling a natural transformation in the SF solves anything. I think I understand the second option, which seems like a good one.

**Comment by jdegoes** [comment]
Here are my general thoughts on the approach:

1. Because the query language appears in the output of the `SF`, there is no way to query except in response to user input. This limitation is too severe if initializers / finalizers are dropped from pure `SF`.
2. There is no locality to the query language, which is most evident in the fact that the natural way to implement it is at the top level (Option 1), with a fully imperative, effectful, and non-composable solution. A desirable property is being able to direct a query to a particular component, but in this approach, there are no components, just global languages that will have to embed disparate "component identity" information in order to address queries to specific components. This is not declarative or composable.
3. A desirable property is that a parent could use child query languages without leaking such implementation details, in the same way a function can call various other functions without that knowledge escaping. It's not fatal, but this property is definitely not present in this design.
4. It feels like there's a sort of "accretion of features" happening. For example, one can imagine that `i` fed to a signal function is in fact a query directed at that component — so we have that query mechanism, plus another "global query mechanism" which is expressed by returning query requests in response to user input. It feels like in a "settled" design, these would somehow unify into a single mechanism.
5. As for option (2) and (3), embedding the natural transformation, this is no more expressive than simply "inlining" the natural transformation and having the "query language" expressed in `m`. Interestingly, this is already possible, that is, one can write imperative `getTextContent :: DomId -> Aff _ String` today, which looks for the Ace component installed on that `id`, and returns the textual content. And exactly as in this proposal, one can do this only in response to user input.

I do like the idea of typed query languages for components, but I think this design does not give us anything which is not already expressible in a more direct fashion (5). Maybe the design just needs to settle or some unification needs to happen, as per (4).

**Comment by paf31** [comment]
> one can do this only in response to user input

User input, or external input from the driver function. Are there any other cases where we need to query a component? We could even expose the "query function" just like we expose the driver function right now.

We have the same issue with any query language that we have with inputs - we want them to be composable, and still be able to hide their internal structure. Something like `combine` solves this problem with inputs - we can compose components, taking the sum of their input types. Sibling components don't get to see each other's input type, and we can use `Inject1` to compose inputs. I don't see why we couldn't do the same with queries, using `Inject` instead.

The really ugly bit for me is interpreting queries. Components don't really identify the bit of the DOM which they "own", so every query has to work from the root down, using something like `simple-dom` or jQuery to find the element it wants to work on.

**Comment by jdegoes** [comment]
>  We could even expose the "query function" just like we expose the driver function right now.

Right now the driver function is being threaded through the application as a way of allowing parts of the app to leak information to other parts (much the same way you have Channels / Mailboxes in some FRP, global black holes that can be used to pass information to far away parts of the app in a way that is not reflected in type signatures). It's actually a sort of an anti-pattern I'm seeing emerging. Passing around these global "driver" and "query" functions should not be encouraged, in fact, I'd say until there's no reason to pass them around, we still have work to do.

Types should locally reflect communication, global magic like driver or query functions should not even be used by the application.

> Components don't really identify the bit of the DOM which they "own", so every query has to work from the root down, using something like simple-dom or jQuery to find the element it wants to work on.

That was one nice thing about the old `p` approach, you had a way of addressing specific children, which could form the basis of localized communication.

In practice, `p` tended to be used like this:

```purescript
data Component = AceComponent CellId | ...
```

i.e. pretty much exactly like an address. Wasn't perfect, though, since you had no way of knowing if such a `p` existed, but at least it provided a handle on which communication could be built. I'm sure there are more clever ways of doing that than we attempted.

>  I don't see why we couldn't do the same with queries, using Inject instead.

Again, the current formulation of this is no more expressive nor any more declarative than simply using functions like `getTextContent :: DomId -> Aff _ String`, which we can *already do today*. No need to wrap those things up in a ADT and push it up to the top of the tree just so we can then globally interpret through conversion to `Aff`. While providing modest benefits to testability, it doesn't really move the needle in terms of usability, compositionality, or encapsulation, and will actually have negative effects on performance and usability. Do you disagree?

There's promise in typed interface language for components, but I don't think we've hit upon the right formulation yet (if such a formulation exists).

**Comment by jdegoes** [comment]
Spent half an hour playing around with types. The most interesting thing is that a natural transformation emerges quite naturally if you allow a component to provide a DSL `f` and require a DSL `g`.

```purescript
-- | p - type of placeholder
-- | f - provided dsl
-- | s - type of state
-- | i - type of inputs generated
-- | g - required dsl
data Component p f s i g = {
  initial :: s,
  render  :: s -> HTML p i,
  update  :: i -> g s,
  query   :: forall q. f q -> s -> g q }
  
type AceComponent eff = Component Void AceQuery AceState AceInput (Eff (ace :: ACE | eff))

newtype AceState = AceState { id :: String }

data AceQuery eff a = GetContent (AceState -> Eff (ace :: ACE | eff) a)

getContent :: AceQuery String
getContent = AceQuery (\s -> ... )

aceEditor :: forall eff. String -> AceComponent eff
aceEditor id = {
  initial : AceState { id : id },
  render  : \state ->
    case state of
      AceState { id = id } -> ...,
  update : \input -> ...,
  query  : \query state -> 
    case query of
      GetContent f -> f state }

installAll :: forall p f f' s s' i i' g g'. (Ord p) =>
  Component p (Coproduct f g') s i (Coproduct g f') ->
  (p -> Component Void f' s' i' g') -> 
  Component Void f (Tuple s (Map p s')) (Either i (Tuple p i')) g

data CellType = AceEditor String | ...

notebook = container `installAll` installer
  where installer (AceEditor id) = aceEditor id
```

**Comment by jdegoes** [comment]
Oh, and I figured out one way to unify `i` and `f`: `i` is just a command that updates state (optionally using DSL `g`), so:

```purescript
data Component p s f g = {
  initial :: s,
  render  :: s -> HTML p (f (s -> s)),
  query   :: forall q. f q -> s -> g q }
```

This means the same `query` interface works for updating a component's state as well as querying its state, which cleans it up quite a lot. 

Not sure how this looks translated into `SF` machinery.

**Comment by paf31** [comment]
> I figured out one way to unify i and f

The only difference is that `i` causes a render to happen, but `f` doesn't necessarily (we should be able to query a widget without rerendering it).

I was thinking that it might be helpful for locality to be able to turn a `Component` into a `Widget`. That way, we would be able to have components which managed their own `HTMLElement` and which get diffed as a single unit. It might make composition of handlers a bit more pleasant since inputs won't have to bubble all the way to the top.

**Comment by jdegoes** [comment]
> The only difference is that i causes a render to happen, but f doesn't necessarily (we should be able to query a widget without rerendering it).

Sure, but when you split apart into `render` and `query` functions (as above), you have explicit control over re-render, and the algorithm can choose to re-render only after state has been modified through an input event; i.e. when you feed query `f (s -> s)`, you're going to get back a state updating function in `g`, and can then choose to re-render based on that.

As an aside, it occurs to me the above signatures do not permit querying to modify the state, except through production of an input. I'm not sure if that's good or bad but I'll think about alternatives.

> I was thinking that it might be helpful for locality to be able to turn a Component into a Widget.

I think the distinctions between Widget, Component, and SF are all unfortunate and inhibit composition. But given these distinctions, I can see where this bundling might be quite useful -- although I would need more input from @cryogenian, @garyb, @puffnfresh etc to confirm.

**Comment by jdegoes** [comment]
Attempt at formulating the above without explicit state, using SF & friends:

```purescript
data HtmlT p m a = HtmlT (m HTML p a)

data Component p f g = Component (forall q. SF1 (f q) (HtmlT p g q))
```

Not entirely successful since the component is re-rendered on every query... which is basically worst case behavior (what if you query it 10 times in a row?).

A different approach, far simpler:

```purescript
class Renderable p f where
  render :: f (HTML p (f Unit))

data Component p f g = Component (forall q. SF1 (f q) (g q))
```

The idea being that you can only run a component if you can tell it to render itself. Placeholders feel a bit hacky in this representation but everything else looks super clean. Also HTML only generates write-only commands that have unit return values (which makes sense).

**Comment by paf31** [comment]
I'm not sure I understand `Renderable` or "you can only run a component if you can tell it to render itself". What would an example instance look like?

**Comment by jdegoes** [comment]
`f` is just a DSL:

```purescript
module (FormDSL(), ...) where

newtype FormState = FormState {}

data FormDSL a = Render (FormState -> a) | Submit (FormState -> a)

submit :: FormDSL Unit
submit = Submit (const unit)

instance renderFormDSL :: Render FormDSL where
  render = Render (\state -> {- build HTML which generates `submit` -} )

instance functorFormDSL :: ...
```

The `Renderable` type class requires that the DSL include a query that can produce "rendered" HTML, whose "input" events are themselves part of the DSL.

Thus `runUI` can require that any component passed to it at least be able to accept a query to render itself (and return the rendering in some functor / monad that it can deal with).

**Comment by paf31** [comment]
Isn't there a `Free` in there somewhere?

**Comment by jdegoes** [comment]
Yeah, free or finally tagless or something... or else you can't sequence the inputs.

**Comment by paf31** [comment]
I spent a little time yesterday trying to figure out how to make `yield` into a query operation, but I'm not sure if it can be done. The best I could come up with was:

```purescript
data SF f m i o = SF 
  { render: i -> m { output :: o, next :: SF f m i o }
  , query: forall a. f (m a) -> m { result :: a, next :: SF f m i o }
  }
```

`EventT f i m` would be `FreeT (EventM f i) m` where `data EventM f i a = Yield i a | Query (f a)`, and at the top level we would require `SF f (Eff eff) i (HTML f i)` where `HTML f i` embeds event handlers of type `EventT f i (Aff eff)`.

`SF` would no longer have `Applicative`, `Choice`, `Strong` etc. unless we fix `f ~ Const Void`, but we could provide alternative combinators which would take `Coproduct`s of the corresponding `f`s instead. We get generalizations of `Applicative`, `Choice` and `Strong`. I haven't worked out `mergeWith` yet, but I think it will go through.

Widgets can be implemented by taking `m ~ Eff (dom :: DOM | eff)` and pure components can keep `m` polymorphic.

**Comment by jdegoes** [comment]
Subsumed by #138, which I think takes many ideas from this thread but with simpler types, localized communication, etc.
