### ISSUE TITLE
Provide way to give Halogen's state to a component

### ISSUE THREAD

**Issue by puffnfresh** [slamdata/purescript-halogen#136]
In slamdata/slamdata we use a lot of Ace components. The components depend upon global state in a few different ways.

Eventually we just provided a hack to give the application's state to each Ace component. We have something like this:

```purescript
main :: Eff (NotebookAppEff (ace :: ACE)) Unit
main = onLoad $ void $ do
  stateKnot <- newRef initialState
  let post = postRender stateKnot aceKnot
  Tuple node driver <- runUIWith app post
  D.driver stateKnot driver
  where
  postRender sKnot input node driver = do
    modifyRef sKnot (flip updateState input)
    A.acePostRender sKnot input node driver
```

And then in the Ace component we read the RefVal, create and change the Ace components and set up hooks to provide further Input values back to the driver.

Problems with this solution:

1. We run updateState twice on each input, maintaining two copies of the current state in different places.
2. We use a RefVal to thread things around manually.

**Comment by puffnfresh** [comment]
I'd also like to limit what is given to components, maybe by just contramapping with a lens.

**Comment by garyb** [comment]
Having access to the state via the `RefVal` was indeed extremely useful, but having the two independent copies of the state ended up being my biggest problem with it - the `RefVal` is updated in the post-render hook, so if you use the driver to update the state, the change doesn't happen immediately from the point of view of the function doing the driving, so you have to apply the change to the `refState` too [in some cases](https://github.com/slamdata/slamdata/blob/a894f074dba3e1814b774c70f2d073743370b1b8/src/Driver/Notebook.purs#L157-L163).

The problem in the linked case above actually happens because the router picks up the URL change, but the post-render hook hasn't triggered the state update, so the routing misbehaves as it operates on an old copy of the state...

This is basically all just an artifact of how we expose the state though, and not really the core of the problem.

**Comment by puffnfresh** [comment]
@garyb I didn't even know about that hack. Even worse than I thought :crying_cat_face:

**Comment by jdegoes** [comment]
I am not sure if this is addressed by #138. Parent components have visibility into the child's state, but child components do not. One could write an install combinator so that a child has a view of the parent's state. But I'm wondering if this will even be needed in the new design or if there would be better ways of solving the same problems.

**Comment by garyb** [comment]
I'd have to check to be sure, but I think with "component state" this problem is solved, the only reason the global state is needed currently is as that's the only kind of state we have at the moment. If not, the parent can always push the relevant part of its own state into the child component as needed.

**Comment by jdegoes** [comment]
Good point, we could add a few functions to update child state.
