### ISSUE TITLE
Missing `InstalledComponentP` type?

### ISSUE THREAD

**Issue by parsonsmatt** [slamdata/purescript-halogen#179]
I'm writing a port of the Elm architecture to purescript-halogen and I've got the following code:

[CounterRem.ui](https://github.com/parsonsmatt/purs-architecture-tutorial/blob/master/src/Example/CounterRem.purs#L28-L32):

```
ui :: forall g p. (Plus g)
   => InstalledComponent Unit Counter.State Input Counter.Input g CounterSlot p
ui = install withRemove mkCounter
    where
        mkCounter (CounterSlot _) = createChild Counter.ui (Counter.init 0)
```

Now I want to install that into another component, that has a list of these counters:

[Example.Four](https://github.com/parsonsmatt/purs-architecture-tutorial/blob/master/src/Example/Four.purs#L46-L51):

```
listRemUI :: forall g p s. (Functor g)
          => ParentComponentP State _ Input Counter.Input g CounterSlot p
listRemUI = component' render eval peek
-- .......

-- ui :: forall g p. (Plus g)
--    => InstalledComponent State Unit Input Counter.Input g CounterSlot p
-- ui = install' listRemUI mkCounter
--     where
--         mkCounter (CounterSlot _) =
--             createChild Counter.ui (installedState unit)
```

The commented out UI function, when uncommented, gives the following type error:

```
Error found:
Error in module Example.Four:
Error in value declaration ui:
Error checking that type
  _0 -> _1
subsumes type
  Example.Two.CounterSlot -> Halogen.Component.ChildState<_2,Example.CounterRem.Input,_3,_4>
Error checking that type
  _1
subsumes type
  Halogen.Component.ChildState<_2,Example.CounterRem.Input,_3,_4>
Error checking that type
  _1
subsumes type
  Data.Tuple.Tuple (Halogen.Component.Component<_2,Example.CounterRem.Input,_3> _4) _2
Error at /home/matt/Projects/purs-architecture-tutorial/src/Example/Four.purs line 48, column 6 - line 49, column 5:
  Cannot unify type
    Example.CounterRem.Input
  with type
    Data.Functor.Coproduct.Coproduct Example.CounterRem.Input (Halogen.Component.ChildF Example.Two.CounterSlot Example.Counter.Input)
See https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify for more information, or to contribute content related to this error.
```

Which makes it seem to me like I need an InstalledComponentP type? If I'm wrong I'd love to know :)

**Comment by garyb** [comment]
I think the problem here is the `InstalledComponent` synonym isn't perhaps as useful as I thought - I encountered the same thing while making examples for the new README (almost done!).

Here's the relevant chunk from the new README:

---

This process of installation can be repeated to have multiple levels of nesting, however if the hierarchy of components in your application is going to be deeply nested it is usually better to define your own type synonyms rather that using `InstalledComponent`. For example, if you have a 3-level deep hierarchy:

``` purescript
-- The state, query algebra, and slot types for our components
type StateLast = ...
data QueryLast a = ...
newtype SlotLast = ...

type StateMiddleP = ...
data QueryMiddleP a = ...
newtype SlotMiddle = ...

type StateTop = ...
data QueryTop a = ...

-- The bottom-most child is a “normal” component
last :: forall g p. (Functor g) => Component StateLast QueryLast g p

-- The parent component definition for the middle layer:
middleP :: forall g p. (Functor g) => ParentComponent StateMiddleP StateLast QueryMiddleP QueryLast g SlotLast p

-- We now want to define synonyms for our composite state and query algebras:
type StateMiddle g p = InstalledState StateMiddleP StateLast QueryMiddleP QueryLast g SlotLast p
type QueryMiddle p = Coproduct QueryMiddleP (ChildF SlotLast QueryLast)

-- And then use the synonyms in the definition for the `InstalledComponent` equivalent for the middle layer:
middle :: forall g p. (Plus g) => Component StateMiddle QueryMiddle QueryLast g p
middle = install middleP mkLast
  where
  mkLast = ...

-- Now we can use these synonyms in the top layer so we only have to describe the types for the previous installed layer:

topP :: forall g p. (Functor g) => ParentComponent StateTop StateMiddle QueryTop QueryMiddle g SlotMiddle p

top :: forall g p. (Plus g) => InstalledComponent StateTop StateMiddle QueryTop QueryMiddle g SlotMiddle p
```

---

Hopefully that's helpful? If not let me know and I'll try to clarify.

**Comment by parsonsmatt** [comment]
I'm trying to implement the type synonyms ([code right here](https://github.com/parsonsmatt/purs-architecture-tutorial/blob/master/src/Example/CounterRem.purs)), and getting the following error:

```
Error found:
Error in module Example.CounterRem:
Error in value declaration ui:
Error checking kind of type
  forall g p. (Control.Plus.Plus g) => Halogen.Component.Component Example.CounterRem.StateMiddle Example.CounterRem.QueryMiddle Example.Counter.Input g p
Error checking kind of type
  forall g p. (Control.Plus.Plus g) => Halogen.Component.Component Example.CounterRem.StateMiddle Example.CounterRem.QueryMiddle Example.Counter.Input g p
Error checking kind of type
  forall g. (Control.Plus.Plus g) => Halogen.Component.Component Example.CounterRem.StateMiddle Example.CounterRem.QueryMiddle Example.Counter.Input g p
Error checking kind of type
  (Control.Plus.Plus g) => Halogen.Component.Component Example.CounterRem.StateMiddle Example.CounterRem.QueryMiddle Example.Counter.Input g p
Error at /home/matt/Projects/purs-architecture-tutorial/src/Example/CounterRem.purs line 36, column 1 - line 38, column 1:
  Cannot unify kind
    *
  with kind
    (* -> *) -> * -> *
```

It seems like it isn't liking the type synonyms in this context?

**Comment by parsonsmatt** [comment]
Ok, cool! I have a working example of it here: [Example.Four](https://github.com/parsonsmatt/purs-architecture-tutorial/blob/master/src/Example/Four.purs) is a List of Counters, [Example.CounterRem](https://github.com/parsonsmatt/purs-architecture-tutorial/blob/master/src/Example/CounterRem.purs) is a Counter with a remove button added to it, and finally [Example.Counter](https://github.com/parsonsmatt/purs-architecture-tutorial/blob/master/src/Example/Counter.purs) is a counter.

I'm curious if the [`peek`](https://github.com/parsonsmatt/purs-architecture-tutorial/blob/master/src/Example/Four.purs#L38-L44) function is the best way to write that?

**Comment by garyb** [comment]
Oops, that'll teach me to code in the README - I'll add an example of deep-installation to ensure I can reference that code directly and avoid further confusion.

Peek is indeed what you want here I think - the motivating case is basically what you describe here: "a thing that can remove itself from its parent".

Here's another section of the README I'm working on, critiques and error spotting would be much appreciated again :smile::
---

The type of components we’ve described so far only support communication in one way: top-down, from parent to children. Sometimes this isn’t powerful enough to model our user interfaces, for example, if we have a list component and an item component with a delete button, how do we tell the parent to delete the item when the button is clicked?

Allowing children to talk directly to parents would make composition and encapsulation of components problematic, so the solution Halogen adopts is to allow parents to “peek” at the queries their immediate children have received. 

Note _have received_ here – the child component is guaranteed to have already processed the query, Halogen does not offer any kind of mechanism for a parent to interfere with queries that are going to its children, only observe them after the fact. Also note _immediate children_ – the peek function does not give access to all descendants of a component, only the layer immediately below.

[The TODO example](examples/todo) makes use of this technique to allow tasks to “delete themselves” from the list they reside within. First we have a `Remove` constructor in the query algebra for the tasks:

``` purescript
data TaskInput a
  = UpdateDescription String a
  | ToggleCompleted Boolean a
  | Remove a
  | IsCompleted (Boolean -> a)
```

This doesn't actually do anything inside the task so implementing a case for it in the task's `eval` function is trivial:

``` purescript
eval (Remove next) = pure next
```

Now we need to construct a `ParentComponent` for the task list that supports the `peek` operation. This is achieved by using a variation of `component`:

``` purescript
component' :: forall s s' f f' g p p'. Render s f p -> EvalP f s s' f f' g p p' -> Peek s s' f f' g p p' -> ParentComponentP s s' f f' g p p'
```

The additional argument here over the standard `component` is typed `Peek s s' f f' g p p'`, yep... you guessed it, another type synonym!

``` purescript
type PeekP s s' f f' g p p' = forall a. (ChildF p f') a -> Free (HalogenF s f (QueryF s s' f f' g p p')) Unit
```

This is very similar to the `eval` function, but instead of using a natural transformation here we’re throwing away the input type and always returning a `Unit` value. This is necessary so that we don’t have to match every possible case of the child’s query algebra. The `g` type of `HalogenF` has also been specialised to a `QueryF`, as `peek` can only appear in `ParentComponent`s, which are set up the same way.

In addition to using the `component'` constructor our parent component will have to be typed with the synonym `ParentComponentP` rather than the standard `ParentComponent`.

Going back to [the TODO example](examples/todo), here’s the `peek` function for our task list:

```
peek :: Peek State Task ListInput TaskInput g ListSlot p
peek (ChildF p q) = case q of
  Remove _ -> do
    wasComplete <- fromMaybe false <$> query p (request IsCompleted)
    when wasComplete $ modify $ updateNumCompleted (`sub` 1)
    modify (removeTask p)
  ToggleCompleted b _ -> modify $ updateNumCompleted (if b then (+ 1) else (`sub` 1))
  _ -> pure unit
```

`peek` functions always accept a `ChildF p q` value – this allows us to see which child received the query (the `p` value is the slot placeholder value) and the query that was processed (the `q value`).

Here we’re observing when the child has processed a `Remove` query, and when doing so we remove it from the parent’s state and also revise the count for the number of completed and pending tasks. We also observe `ToggleCompleted` queries and likewise update the completed task count accordingly.

This usage of `peek` illustrates another fairly subtle point about its usage: when observing `Remove` we a send a further query to the child in question to check on its completion state, however this does not trigger an infinitely recursive `peek`: any queries to children made inside `peek` are not re-observed by `peek`.

**Comment by parsonsmatt** [comment]
> Also note immediate children – the peek function does not give access to all descendants of a component, only the layer immediately below.

hmm, if I patter match on the coproduct, then I can dig deeper into the component heirarchy. Using my example code, this works:

```
peek :: Peek State (Counter.StateMiddle g p) Input Counter.QueryMiddle g CounterSlot p
peek (ChildF counterSlot queryAction) =
    case runCoproduct queryAction of
         Left (Counter.Remove _) ->
             modify (removeCounter counterSlot)
         Right (ChildF slot' counterAction) ->
             case counterAction of
                  CC.Increment _ -> pure unit
```

Otherwise that looks great :D

**Comment by garyb** [comment]
Ah yes, oops! That was something that I meant to look at again, at one point we did hide those descendant queries from `peek`. I was thinking about tweaking peek anyway so that you don't have to deconstruct `ChildF` yourself, and instead it would be passed the `p` and `q` values as two separate arguments.

Thanks!

**Comment by parsonsmatt** [comment]
I think I would probably only want to be able to view the immediate descendants -- anything more and I've likely made a design problem :stuck_out_tongue: It would definitely be more convenient to use if it only used the `p` and `q`, especially if it only gave you one level of access by default. This would be a decent bit nicer to write, but I don't know how feasible it'd be!

```
peek :: Peek State (Counter.StateMiddle g p) Input Counter.QueryMiddle g CounterSlot p
peek p (Counter.Remove _) = modify (removeCounter p)
```

In any case, I think my question is answered -- I'll close the issue :) Thanks for the help!

**Comment by garyb** [comment]
Yeah, that kind of thing is exactly what I had in mind :)

Looking into it now I remember why it's not already like that, but I think it should be doable with some wrestling of the internal types.

**Comment by garyb** [comment]
It turns out `peek` in its current form may be the best thing for now - if you have an action that you want to "bubble up" past the immediate parent, peeking a deeper level is the only way that is possible currently. `peek` can't execute queries on the current component, so there is no way to make the action observable to the next level up's parent. Will revisit this for 0.6 perhaps...
