### ISSUE TITLE
component' is not exported from Halogen.Component

### ISSUE THREAD

**Issue by cdepillabout** [slamdata/purescript-halogen#199]
In the 0.5.1 release, it looks like `component'` is not exported from the `Halogen.Component` module.  Is this correct?

https://github.com/slamdata/purescript-halogen/blob/master/src/Halogen/Component.purs#L82

Without `component'`, is there any way to make a `ComponentP`?  Or is that just some internal machinery and shouldn't be used by end users?

From a cursory glance over the code, it's not immediately obvious why ComponentP is not exported but RenderP is.

**Comment by garyb** [comment]
Not exporting `component'` is intentional as it's not a very useful function to expose publicly - the `ComponentP` version of the type is only used internally, so there's not really a good reason to expose the smart constructor for it.

`RenderP` is exported as it is used inside `Render` and `RenderParent`, and likewise `PeekP` inside `Peek` and `ComponentP`... if the compiler let me, I wouldn't be exporting `ComponentP`, `RenderP`, or `PeekP` and instead would only provide the "public" synonyms, but currently it is required for typechecking to succeed.

There's a bit of discussion about what should or shouldn't be allowed for synonyms in purescript/purescript#1526. It's on hold for 0.7.5 but we're going to revisit before 0.8.

**Comment by cdepillabout** [comment]
Okay, that makes sense!  Thanks!
