### ISSUE TITLE
Use virtual-dom Thunks with components

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-halogen#253]
Right now we memoize the render result, but this doesn't save us as much as it could since virtual-dom still diffs it. We should probably be using `Thunk`s to eliminate that cost.

**Comment by garyb** [comment]
Good idea :+1:

**Comment by natefaubion** [comment]
Actually, I don't think this is necessary. The first check in the virtual-dom diff algorithm is a referential comparison. It already assumes that two trees are equal if their roots are the same.

**Comment by natefaubion** [comment]
My previous comment was incorrect. The memo is a map to `HTML`, and not virtual-dom nodes, so it will never trigger a referential equality during the patch process.

In order to do thunks, maybe you could propagate that information via the slot as something like:
```
type SubtreeThunk f = Tuple Boolean (HTML (SubtreeThunk f) (f Unit)

render :: State s (HTML (SubtreeThunk f) (f Unit)
```

And then in the virtual-dom renderer you can use that to insert a proper `Thunk`.

**Comment by natefaubion** [comment]
A `Boolean` won't quite work for a couple of reasons. Because it's possible in Halogen to move a component around and still trigger the cache, you can't just always emit some generic thunk. I think it's also technically possible to move one component into the same DOM position as a completely different component. You can't really propagate slots because they are local to the component. Maybe you could `toForeign` both the component definition we keep in the map and the slot and do ref equalities in the thunk? Due to the way virtual-dom works I don't think there's a way to avoid some sort of ref equality.

**Comment by garyb** [comment]
Using something like `Foreign` is probably what we'd have to do here, since Halogen is theoretically agnostic about render target, so we can't go and embed `VTree` types in the components. :wink:

I think the ref equality is still slightly tricky too, as you can reuse the same component definition in multiple places potentially with the same slot value if they have different parents - so you'd have to accumulate all the parent slots in the tree up to that point too.

Maybe there's something in the old approach of the virtual dom renderer using a `Ref` with a lookup to memoize chunks of HTML for components rather than trying to store that in the component tree again too?

**Comment by garyb** [comment]
#280
