### ISSUE TITLE
Access child's state without query

### ISSUE THREAD

**Issue by user471** [slamdata/purescript-halogen#258]
Is there any way to access child's state without query?
So, instead of 

```
a <- query (TickSlot "A") (request GetTick) 
b <- query (TickSlot "B") (request GetTick)
```

It could be

```
TickState a <- getState (TickSlot "A")
TickState b <- getState (TickSlot "B")
```

**Comment by garyb** [comment]
No, and even if there was the result would still have to be a `Maybe`, as there is no guarantee that a child component is present for any given slot address.

You could write your own function to do this, it's not _forbidden_, but we don't provide one by default as it bypasses the idea of components being encapsulated units.

**Comment by garyb** [comment]
Oh, actually, sorry, you can't write a function to do this easily - it would involve reimplementing `parentComponent`, as that transforms `HalogenF` in such a way that `Get` gives you the parent component's inner state, not its `InstalledState` value.

**Comment by user471** [comment]
>but we don't provide one by default as it bypasses the idea of components being encapsulated units.

But, you already use component state's type
```
eval :: EvalParent Query State TickState Query TickQuery g TickSlot
```
How is it encapsulated unit?
This function just return instance of ```TickState```

**Comment by garyb** [comment]
Yeah, that mistake has already been pointed out, it should be possible to remove the child state from the type synonym in theory.

**Comment by user471** [comment]
Also, you can just create Query and return full state.

```
data TickQuery a
  = Tick a
  | GetState (TickState  -> a)
 eval (GetState continue) = do
    state <- get
    pure (continue state)
```
The only problem is more code.

**Comment by garyb** [comment]
Yep, that's a solution. In those cases the child component is choosing to break the idea of having a self contained state, rather than it being a globally imposed rule from above, so that's fine.

A big part of the rationale for the current Halogen design is that a state object for each component is not enough to capture the state of any possible component: "3rd party" components (non-PureScript, non-Halogen JS components) can be wrapped in a Halogen component and then provide access to the native component API to get information about the state, as it is impractical (or impossible) for Halogen to maintain a complete and up-to-date state value for these kind of components.

**Comment by user471** [comment]
I completely understand the idea. But for a small project is could be overkill. Instead of just return full state you need to create millions of queries and evals.

**Comment by garyb** [comment]
Closing this as the direction things have gone now it's "even more impossible" to access child state directly, since state is existential.
