### ISSUE TITLE
Mutually Recursive Components

### ISSUE THREAD

**Issue by jamesmcnamara** [slamdata/purescript-halogen#299]
Is there any way to create mutually recursive components, such that a `Foo` component has a slot for a `Bar` component, and a `Bar` component has some optional slot to its own `Foo` component?

Note that I don't mean they have slots to each other, but that the `Bar` component has a sub-component which is a `Foo`, such that the component tree is arbitrarily deep, but finite and directed, e.g. 

``` purescript
data Foo = Foo {
    bar: Bar
}

data Bar = Bar {
    mfoo: Maybe Foo
}
```

The issue I keep running into is that the child's state and child query type parameters (to `ParentHTML`, e.g.) seem to explode in this paradigm.

Is this relationship possible, or is there an equivalent way to spec mutually recursive data types?

**Comment by garyb** [comment]
To make the types work out you could perhaps use some existential hiding, I think that's the only way you'll be able to avoid having an infinite type, since something like [`Mu`](https://github.com/slamdata/purescript-fixed-points/blob/v0.2.0/src/Data/Functor/Mu.purs) won't work here either.

**Comment by jamesmcnamara** [comment]
Thanks so much!

As a follow up, which type would you expect needs to be quantified over to make this work? The childState, or the childStateP types? Would you quantify over it in the type of ParentStateP? Would I need to create a typeclass to capture the functionality of the hidden type?

As a simplest motivating example, here's simple components drawn up for the data types described above. Without the slots, it compiles fine. Where roughly do you think there needs to be existentials?
```purescript
module Main where

import Prelude

import Control.Monad.Eff (Eff())
import Control.Plus (Plus)

import Data.Functor.Coproduct (Coproduct())
import Data.Generic (Generic, gEq, gCompare)
import Data.Maybe (Maybe(..), maybe)

import Halogen
import Halogen.Util (runHalogenAff, awaitBody)
import Halogen.HTML.Indexed as H
import Halogen.HTML.Properties.Indexed as P
import Halogen.HTML.Events.Indexed as E

data Foo = Foo {
    bar :: Bar
}

data Bar = Bar {
    foo :: Maybe Foo
}

data FooQuery a
  = FooNull a

data BarQuery a
  = BarNull a

initialState :: Maybe Foo
initialState = Just (Foo { bar: Bar {foo: Just (Foo {bar: Bar {foo: Nothing}})}})

newtype BarSlot = BarSlot String
newtype FooSlot = FooSlot String

derive instance genericBarSlot :: Generic BarSlot
instance eqBarSlot :: Eq BarSlot where eq = gEq
instance ordBarSlot :: Ord BarSlot where compare = gCompare

derive instance genericFooSlot :: Generic FooSlot
instance eqFooSlot :: Eq FooSlot where eq = gEq
instance ordFooSlot :: Ord FooSlot where compare = gCompare

type FooStateP g = ParentState (Maybe Foo) Bar FooQuery BarQuery g BarSlot
type FooQueryP = Coproduct FooQuery (ChildF BarSlot BarQuery)

type BarStateP g = ParentState Bar (Maybe Foo) BarQuery FooQuery g FooSlot
type BarQueryP = Coproduct BarQuery (ChildF FooSlot FooQuery)


fooUi :: forall g. (Functor g) => Component (FooStateP g) FooQueryP g
fooUi = parentComponent { render, eval, peek: Nothing }
  where

  render :: Maybe Foo -> ParentHTML Bar FooQuery BarQuery g BarSlot
  render (Just (Foo {bar})) =
    H.div_
      [ H.slot (BarSlot "A") \_ -> { component: barUi, initialState: parentState bar}
      , H.text "Hello from Foo"
      ]
  render Nothing =
      H.p_
          [ H.text "Nothing here!"]


  eval :: Natural FooQuery (ParentDSL (Maybe Foo) Bar FooQuery BarQuery g BarSlot)
  eval (FooNull next) =
    pure next


barUi :: forall g. (Functor g) => Component (BarStateP g) BarQueryP g
barUi = parentComponent { render, eval, peek: Nothing}
  where

  render :: Bar -> ParentHTML (Maybe Foo) BarQuery FooQuery g FooSlot
  render (Bar {foo}) =
    H.div_
      [ H.slot (FooSlot "A") \_ -> { component: fooUi, initialState: parentState foo}
      , H.text "Hello from Bar!"
      ]


  eval :: Natural BarQuery (ParentDSL Bar (Maybe Foo) BarQuery FooQuery g FooSlot)
  eval (BarNull next) = do
    pure next

main :: Eff (HalogenEffects ()) Unit
main = runHalogenAff do
  body <- awaitBody
  runUI fooUi (parentState initialState) body
```
Thanks again!

**Comment by garyb** [comment]
I'm not sure to be honest! I was just throwing it out there as something that came to mind... it was a bit hard to say just going by the description, so thanks for the mockup, I'll take a look and see what I can come up with.

**Comment by jamesmcnamara** [comment]
Hahah totally, I understand!

Definitely let me know if you come up with anything, I've been stuck on this problem for quite a while now.

**Comment by natefaubion** [comment]
I'm not sure it can be done with just existentials over the state. You'd also need to do it over the query, because you'll get an infinite type in either case. I think doing that (if you can) would seal your components off from the world so you couldn't accept inputs (maybe except from yourself?).

Do you have a concrete use case in mind? I know I tried it with a treeview, but I decided that I didn't need to make such fine-grained components, and the whole treeview could just be a single component where just the `render` is recursive.

**Comment by jamesmcnamara** [comment]
I have a component which is something of a dynamic survey. Basically I have multiple question types, one of which is a multiple choice question. A multiple choice question has options, each of which, if selected, may prompt the user with its own follow up question.

Something like:
```purescript
data Question
    = Text String (Maybe String) -- Question text and response
     | MC (List Option)

data Option = Option {
    text :: String 
  , selected :: Boolean 
  , followUp :: Maybe Question
}
```

Each of these types is much bigger in practice, so I need separate components for questions and options, and can't put them all into one component :/ (specifically, action handling becomes a real pain when I need to traverse the tree every time, and I can't find a simple way of making a prism to each leaf).

**Comment by natefaubion** [comment]
It sounds like you could still reduce it to one Halogen component, but you'd need to locally switch to decomposition (using an Elm-like architecture). I think this is an area where it breaks down a bit. Since the full `Component` tree is statically-typed, there's not a way to make a portion of it dynamic without cutting it off from the world. Switching to decomposition essentially lets you make it dynamic because there aren't components in the usual Halogen sense (so you don't get thunking and lifecycles, except at the top level).

**Comment by jamesmcnamara** [comment]
What exactly do you mean by decomposition? Creating local recursive render functions for each component?

```purescript
  fooRender :: Maybe Foo -> ComponentHTML (Maybe Foo) FooQuery g
  fooRender (Just (Foo {bar})) =
    H.div_
      [ barRender bar
      , H.text "Hello from Foo"
      ]
  fooRender Nothing =
      H.p_
          [ H.text "Nothing here!"]
  
  barRender :: Maybe Foo -> ComponentHTML Bar FooQuery g
  barRender (Bar {foo}) =
    H.div_
      [ fooRender foo
      , H.text "Hello from Bar!"
      ]
```

Do they all share one Query Algebra? The only issue I really have here is that action handling has to traverse the entire tree structure for each update, which obscures the code. Is there a way simplify this? Building a prism in the render functions that get embedded in the QueryActions comes to mind,  but I don't know if that is the best solution.

**Comment by natefaubion** [comment]
> but I don't know if that is the best solution.

I don't know if there is a "best" solution, because without recursive components anything is going to admittedly be a bit awkward.

Another option, which is what I'd do in a simple tree view case, is to have a child component for each cell, with the parent component controlling the spine. A cell's children aren't part of the child component, and thus not recursive. The slot for each child is then a cursor to the node in the tree. This is basically turning a tree-view into a list-view. The parent component can then peek on child inputs, and use the cursor to manipulate other paths of the tree.

Sounds like we need to figure out some decent machinery for #221 :)

**Comment by jamesmcnamara** [comment]
Sounds good to me!

If you are satisfied too, this can be marked as closed :)

**Comment by natefaubion** [comment]
Here is a very simple solution to recursive components that involves hiding the type of child state and queries. The trade-off is that you can't do deep queries (you have to go level by level), which I think is fine.

```purescript
foreign import data Private :: *

foreign import data PrivateF :: * -> *

type OpaqueState s f g = ParentState s Private f PrivateF g Private

type OpaqueQuery f = ParentQuery f PrivateF Private

opaque
  :: forall s s' f f' g p
   . Component (ParentState s s' f f' g p) (ParentQuery f f' p) g
  -> Component (OpaqueState s f g) (OpaqueQuery f) g
opaque = unsafeCoerce
```

See here for an example: https://gist.github.com/natefaubion/18ce4523d9d38698ee89afcb130a17a0

This coercion is safe because we already have a properly constructed component. @garyb what do you think of this?

**Comment by garyb** [comment]
That was the kind of thing I had in mind with my suggestion of using existentials. :+1:

I'm not sure that's exactly what @jamesmcnamara was after as it's "just" a self-recursive component, but it has the benefit of the coercion being watertight. This still might work for a mutually recursive case too, if the components in the group all share the same query algebra and state type. That might sound useless, but not necessarily as they can have different `component` implementations still, so maybe that's good enough for the case in question?

**Comment by natefaubion** [comment]
I don't see why you couldn't have mutually recursive components. I just did self-recursive for the simple case. You could swap at `FooQueryP` and `FooStateP` with some other opaque types. And I don't see why you couldn't have a Coproduct in there either: `(Coproduct Foo (OpaqueQuery Bar)`

**Comment by garyb** [comment]
You're probably right, I just figured proving the coercion is safe would take a bit more effort with more layers involved. The `Coproduct` thing occurred to me too but I forgot to mention it!

**Comment by natefaubion** [comment]
Oh, it's more difficult if you don't want to hide _all_ the child query. In the case where you only expose the parent query, it should just always work.

**Comment by garyb** [comment]
In the new Halogen this no longer needs any special thought due to component state and children being existential. :tada:
