### ISSUE TITLE
Module documentation link broken

### ISSUE THREAD

**Issue by seagreen** [slamdata/purescript-halogen#300]
The README links to: http://pursuit.purescript.org/packages/purescript-halogen

But all that page currently shows is: 
> No package named purescript-halogen exists in the database. If you think this is an error, please let us know by opening an issue, or visiting us on #purescript IRC on Freenode.

**Comment by garyb** [comment]
@seagreen thanks, it was published on Pursuit up until yesterday when an update was run.

@hdgarrood any ideas... I assume it failed to re-import for some reason?

**Comment by hdgarrood** [comment]
Yeah, this is the same thing as ace-halogen, it's "Apache 2.0" vs "Apache-2.0" in bower.json. I'm in the process of collecting a list of all the packages that didn't make it back up now too, so everyone will hear soon.

By the way, the vast majority of packages that didn't make it back up are missing because they either didn't declare a license in bower.json or because they didn't use SPDX (eg, here, or BSD3 as opposed to BSD-3-Clause).

**Comment by ryepdx** [comment]
Seeing this same error again.

**Comment by garyb** [comment]
Yeah, the pursuit database was wiped for 0.11, this will be republished when the updated release is made.

**Comment by ryepdx** [comment]
> Yeah, the pursuit database was wiped for 0.11

Wow, that's... inconvenient...
