### ISSUE TITLE
Remove the need to ever force renders

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#302]
Manual render-forcing is an unfortunate side effect of having state changes batched before rendering.

This is required when a parent component has modified its state in such a way that it will bring one or more children into existence, and then immediately wants to query the child(ren) in the same `eval` block, something like:

```
modify (addChild c)
forceRender
query c (action SomeQuery)
```

Ideally we can bake in a mechanism to render as needed before a query, or cause querying to wait until `PostRender` if a state change has been made to the child since the last render.

**Comment by jonsterling** [comment]
Yes please!

**Comment by natefaubion** [comment]
I think there are a couple of ways to go about this:

1. Only batch `Modify` operations, otherwise flush pending renders. If you modify your state (queuing a render), and then follow it by a get, the rendering will be flushed. This would fix the querying children issue, because each child query is preceded by a `get` to lookup the child component. This allows you to have multiple set operations on the parent state, but if you say, query a bunch of children to reset their state (and they have children to reset, etc) then you'll get into the pathological case again, because each subsequent child query will perform another `get` after modifying the state. I guess you could provide some way to batch child queries under a single `get` (this isn't running in parallel, you are just aren't doing multiple gets for child state), but this is awkward and a pretty awful abstraction leak.
2. Figure out how to do local component render updates. If you know that a render is completely local to a component after a state change, then you don't even need to worry about it. Issuing a bunch of child queries will only cause those specific components to rerender (rather than the whole tree). This is a bit pie-in-the-sky, and while "possible" I have no idea how to plumb this 😛.

Causing querying to defer to post-render if there's a pending render still carries the same pathological case as (1). So if you query a bunch of children sequentially in a way that updates their state, you'll get a full render in between each child query. A MonadPar instance might help with this? I guess if you could run queries in parallel, you could recover from the pathological case.

**Comment by natefaubion** [comment]
It's pretty awful, but you could add some internal stuff to HalogenF like `EnterChildQuery` and `LeaveChildQuery`. This would allow the driver to track the full stack of child queries and batch as needed.

**Comment by natefaubion** [comment]
After thinking about it a bit more, and mocking up solutions, the main issue is that the Driver just doesn't have enough information to perform the optimization with what `HalogenF` gives you. Because child components are composed away, the Driver just thinks it's dealing with a single component and can't make intelligent decisions about batching. The `Enter/Leave` thing above "works", but it really sucks to add that as part of `HalogenF` because `HalogenF` is user-facing, and I think it would make it a not-so-well-defined of an algebra. But if we make an additional, internal algebra `DriverF` that contains explicit instructions around rendering (or component structure) we could then transform `HalogenF` as part of the normal component machinery. This moves more of the optimization into the component machinery rather than the Driver, but I think it makes quite a bit more sense, and keeps it out of any user-facing code.

**Comment by garyb** [comment]
That sounds reasonable. Where does `DriverF` come in then, in the type of `eval` in the `Component` record?

**Comment by natefaubion** [comment]
Yes I think so. The `ComponentSpec` stuff would be the same, you just map to `DriverF` before building the component record. `DriverF` is essentially just `Coproduct (HalogenFP ...) StackF` where `data StackF a = Push a | Pop a | RenderPending a ...`.

**Comment by natefaubion** [comment]
Ugh! This obviously doesn't work, since if you package up a Component with `DriverF`, its infectious. So if you try to `queryComponent` a child, it will be in `DriverF`, necessitating everything else to be in `DriverF`.
