### ISSUE TITLE
Reconsider the behaviour of `ref`s

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-halogen#304]
When working on the slider stuff with @beckyconning we ran into a problem where a `ref` was being kept in the state, but then `set` was being used in a query, reverting the stored ref.

Now, that's not really surprising, since this was the reason I was hesitant to introduce `set` in the first place, but given how many places we had `modify (const ...)` it seemed like we may as well have it anyway... but that's not really the issue here, it's also that managing `ref`-triggered values is something that will be replicated in almost exactly the same way anytime `ref` is used, so can we not handle some of that internally? The way `ref`s currently work is also open to abuse because they sort-of act like initializers/finalizers, except when they don't, and despite it being documented it's not obvious from the way they seem to behave when used in the trivial case.

So the proposal is perhaps we could change it so refs do not raise queries that need handling, but instead accept a key value of some kind and then are stored in a section of state that is managed by Halogen. We could then change it so that refs are only fetchable by a query, something like `getRef :: refkey -> ComponentDSL s f g (Maybe HTMLElement)`. This essentially gives us the same interface as we currently have when it comes to retrieving `ref`-captured elements from the state, but removes the need for managing that stuff manually, and would prevent misuse of the `Ref` queries since they would be handled internally.

I'm not sure what `refkey` should be, whether we want yet another type parameter, or whether we just say it's a string/newtyped string and leave it at that.

**Comment by natefaubion** [comment]
The only thing I'd say is that the current setup gives you information about when DOM elements are entering and leaving, which may be necessary for setup/cleanup if that happens over the lifecycle of a component. If we just keep it in a map, we don't have that information.

There's no reason why we can't wrap all component state in something else for this bookkeeping. It's just difficult to propagate that information without requiring all components to have an additional `Coproduct` for some internal Query. This just makes peeking a bit harder because you have to go through another layer. If we wrap state, we have to do more work in mapping the state back and forth (it should at least be total). One possibility is have a double-secret-unsafe map for storing this references, and propagate this through the component `Tree` stuff to the virtual-dom renderer, wherein we close over the map when we create the ref hook, and the hook just mutates it.

**Comment by garyb** [comment]
> If we just keep it in a map, we don't have that information.

Yeah, I realise it's a tradeoff. I figured the case above could still be handled by making a sub-component that is responsible for its own setup/cleanup using lifecycle hooks instead. I'd be nervous about a component using the `ref` that way myself - unless you really know what you're doing it's not really safe for this kind of thing, and probably you and I are the only ones who really understand the ref/initializer/finalizer interactions as it stands.

**Comment by garyb** [comment]
We went ahead and did this in the end. It's nice. (e84ce3737453754322599ff0aa2554a18ba8b77e + some later commits to improve things with `InputF`)
