### ISSUE TITLE
The .gitignore for the repo doesn't exclude outputs from the examples.

### ISSUE THREAD

**Issue by philderbeast** [slamdata/purescript-halogen#329]
I made a change to fix an issue to do with the examples but find that there are thousands of pending changes. The .gitignore for the repo doesn't exclude outputs from the examples.

**Comment by philderbeast** [comment]
When I build the multicomponent example, in each GUI git client I have, I see 7227 non-versioned files, mostly in the examples/multi-component/node_modules folder. I can see the same thing on the command line with ...

`>git status --untracked-files`

**Comment by philderbeast** [comment]
To reproduce the problem, run `npm install` from the folder `examples/multicomponent`, ignoring the advice in `examples/readme.md` to do this install from the repo root. Then check for untracked files that aren't ignored with `git status --untracked-files`.

**Comment by garyb** [comment]
Yeah, sorry for the confusion here - the individual example `.gitignore` files don't cover `node_modules`, but they should - my only objection to the PR you opened is that we should perhaps update the example-level files rather than the root one (it doesn't really matter I guess, but since we have them per example it seems reasonable to apply example-related rules there).
