### ISSUE TITLE
Please add snabbdom integration :)

### ISSUE THREAD

**Issue by kristianmandrup** [slamdata/purescript-halogen#350]
Please make it easy to swap the VDOM implementation.

[SnabbDOM](https://github.com/snabbdom/snabbdom) is the new hotness!! Used by Cycle.js (MotorCycle) and Vue2...

[snabbdom article](https://medium.com/@yelouafi/react-less-virtual-dom-with-snabbdom-functions-everywhere-53b672cb2fe3#.lxre6thfu)

**Comment by natefaubion** [comment]
In the upcoming Halogen it is possible to abstract over both the HTML rep and backend driver, so this is in theory possible. It's unlikely we will add native snabbdom support as part of core Halogen (snabbdom lacks a comparable widget-like abstraction so its hard to implement the local updates). Though we will likely add support for https://github.com/slamdata/purescript-halogen-vdom

**Comment by kristianmandrup** [comment]
Wow! That was a quick response!!! widget-like abstraction? I thought VDOM was just an abstract tree abstraction!? Anyways... I trust your judgement and looking forward to `purescript-halogen-vdom` which sounds awesome!!!

**Comment by natefaubion** [comment]
By widget-like abstraction, I mean something that gives an implementer control of the diff process outside of the core framework. In `virtual-dom` this is `Widget`, which we've used to implement local component updates (rather than diffing the entire tree). AFAIK, snabbdom has no such thing, aside from some hacks that take advantage of the way it mutates the tree to tag it with the associated element.

**Comment by natefaubion** [comment]
`purescript-halogen-vdom` is designed to allow for this sort of abstraction by making its

**Comment by kristianmandrup** [comment]
What is the ETA for upcoming release then? :) :D

**Comment by natefaubion** [comment]
Current master is likely going to be what's shipped. @garyb is just working on a new guide.

**Comment by kristianmandrup** [comment]
nice :)
