### ISSUE TITLE
Monadic HTML generation API

### ISSUE THREAD

**Issue by jbracker** [slamdata/purescript-halogen#358]
I love what you did with Halogen, but I'd like to propose an improvement that would ease rendering HTML with Halogen.

Would it be possible to provide a monadic interface for the render function instead of the current combinator based one? To give an example of what I mean, this is the code as I currently write it to render HTML for my components:
```haskell
renderList :: Model -> ContentHTML g
renderList state
      = H.div [ P.class_ $ H.className "some-class" ] 
        [ H.div [ P.classes [ H.className "some-class" ] ] 
          [ H.ul [ P.classes [ H.className "some-class" ] ] 
            [ entry state "Entry 1" SomeEvent
            , entry state "Entry 2" SomeEvent
            ]
          ]
        ]

entry :: Model -> String -> Event -> ContentHTML g
entry state t e
      = H.li_ $ singleton 
      $ H.a [ E.onClick $ E.input_ $ e ] [ H.text t ]
```
I find this reasonable but fairly irritating, because it creates a bracket hell (because of the involved lists).
IMHO the bracket hell makes the code:
* hard to read, 
* ugly and 
* hard to maintain (I have accidentally removed a bracket way to many times when restructuring the HTML tree).

In addition, I am manually passing around the model/state all the time.

To fix these issues I would suggest introducing a monadic interface to generate HTML. This would roughly look as follows (untested code, just to sketch):
```haskell
-- Monad used to generate HTML.
type ContentHtmlM s g a = ReaderT s (Writer (Array (ContentHTML g))) a

-- Combinators to create HTML elements have this form (there would be one for each element like there is right now):
div :: forall s i g. Array ( Prop i ) -> ContentHtmlM s g a -> ContentHtmlM s g a
div props children = do
    -- get state
    state <- ask 
    -- run the generator monad for child elements
    let res = runWriterT $ runReader state children
    -- add the newly generated element to the list of 
    -- sub-elements generated by this computation
    tell $ H.div props $ snd res
    -- Return the result of the sub-element computation
    pure $ fst res
        
div_ :: forall s g a. ContentHtmlM s g a -> ContentHtmlM s g a
div_ m = div [] m

text :: forall s g. String -> ContentHtmlM s g Unit
text t = tell $ H.text t

-- Access to the state without having to pass it around manually.
getState :: ContentHtmlM s g s
getState = ask

-- This API then easily translates to the now used HTML production:
mkHtml :: forall s g. s -> (Array (ContentHTML g) -> ContnentHTML g) 
       -> ContentHtmlM s g Unit -> ContentHTML g
mkHtml state mkParent m = mkParent $ snd $ runWriterT $ runReader state m
```
Using the monadic API the code I presented above would become:
```haskell
renderList :: ContentHtmlM Model g Unit
renderList = div [ P.class_ $ H.className "some-class" ] $ do
  div [ P.classes [ H.className "some-class" ] ] $ do
    ul [ P.classes [ H.className "some-class" ] ] $ do
      entry "Entry 1" SomeEvent
      entry "Entry 2" SomeEvent

entry :: String -> Event -> ContentHtmlM Model g Unit
entry t e = li_ $ a [ E.onClick $ E.input_ $ e ] $ text t
```
This seems a lot nicer to me for several reasons:
* The required indentation of the do-blocks reflects the described dom-structure exactly.
* I don't have to pass around the model by hand everywhere.
* There are __a lot__ less brackets that one can mess up.
* The code is a lot nicer to read and maintain.

From my perspective this is a mainly cosmetic change that could be provided simply through an additional module that exposes the monadic interface and all of the core functions with their type signatures slightly adjusted.

I would attempt to write something like this myself, but I am not very familiar with the internals of the halogen implementation (since I only recently started using it myself). Therefore, I first wanted to ask if anybody sees any problems with adding this and if there maybe is such an interface that I am simply not aware of.

A similar interface to describe HTML is also used in the Haskell  `blaze` packages.

**Comment by garyb** [comment]
We avoided providing a monadic API because of the pretty large performance hit it would impose, for what really seems like fairly negligable readability benefits.

In SlamData at least we've adopted a code style that seems to work pretty well, and I think rarely is confusing when it comes to closing brackets, etc.

Generally it follows this form:

``` purescript
render state = 
  HH.div
    [ ... props ... ]
    [ ... elements ... ]
```

If an entire element fits on one line (< 80 chars) then it's allowed to stay, otherwise both props and children are indented. When indenting for a nested element, then 2 additional spaces are used:

``` purescript
render state = 
  HH.div
    [ ... props ... ]
    [ HH.ul_
    	[ HH.li_ [ ... ]
    	, HH.li_ [ ... ]
    	, HH.li_ [ ... ]
    	]
    , HH.p_ [ ... ]
    ]
```

These rules preserve a visual hierarchy that is easy to scan, and in my book is more readable than actual HTML. Also, this wasn't my proposal, so I'm not just bigging up my own preference here! I did readily adopted the style after reviewing a PR or two using these rules though, as the benefits were immediate for me at least. There is a bit more indentation and height used than in a monadic DSL to be sure, but I don't find the readability suffers for that, as it's mainly the shape you see when scanning the code anyway.

The example you gave in this style:

``` purescript
renderList = 
  HH.div 
    [ P.class_ $ H.className "some-class" ]
    [ HH.div
        [ P.classes [ H.className "some-class" ] ]
        [ HH.ul
            [ P.classes [ H.className "some-class" ] ]
            [ entry "Entry 1" SomeEvent
            , entry "Entry 2" SomeEvent
            ]
        ]
    ]
```

There's nothing stopping someone from writing a monadic style HTML DSL library though, as long as it can produce `render` functions with the appropriate signature . I doubt we'll ever include one as part of the main project however.

**Comment by jbracker** [comment]
Ok, I did not think about performance at all. Is the performance really that much worse? I can see why it is slower with all the binds in between, but I wouldn't have thought it to be that much worse.

I am only writing a small application so I guess I will not notice an actual performance overhead using a monadic interface. Writing a monadic style DSL wasn't that hard after all, it only took me yesterday evening to complete it.

If you do decide to include a monadic DSL for HTML generation just contact me, I have it lying around now.

**Comment by noraesae** [comment]
Today I also tested monadic HTML rendering. The main goal is similar to what @jbracker have implemented, but the difference is that my implementation uses free monad. I leave a link to the repo below.

https://github.com/noraesae/purescript-halogen-free-html

I agree that monadic rendering can be a performance hit. Currently it is just a kind of experiment, and I will see how it performs after it is fully implemented.

**Comment by jdegoes** [comment]
I think this functionality is quite useful, but must be a 3rd party library since it can be added without new features to Halogen core.

**Comment by Roxxik** [comment]
this is a classical make-this -a-monad-because-it-has-nicer-syntax-situation. And regarding this case i'd say the combinators look good enough. 

But for the whole language a way of specifying new syntax is missing and it becomes especially obvious in those situations where people try modeling stuff in obscure ways (with monads, where they're not needed) just to get that nice syntax. In my opinion it should be the other way around.

**Comment by jbracker** [comment]
In general I agree. I suggested this, because I wanted to use monadic syntax which I deem more pleasent in this context and it works nicely. But, of course you are right, there is no requirement for them in this context and writing the HTML without them probably is way more efficient.

But on the other hand I would not say that we are suggesting to use the monad in an obscure manner: The monad fulfills the laws and its purpose. Many of the side-effects modeled with monads don't require them (e.g., State, Readers, Writers, Continuations, etc.) and they can be expressed without monads just as well. But we use monads because they provide a nice and convenient way to express them with some useful combinators and with their syntactic support they look nicer. But this is all a digression from the original topic.

I will close this thread, because the developers made a reasonable decision and people that want to use it can implement (or already have implemented) it on top of the existing API.
