### ISSUE TITLE
Is it possible to query (eval) a child component while rendering?

### ISSUE THREAD

**Issue by dcastro** [slamdata/purescript-halogen#376]
I have a component `BuildTypesList` which is responsible for holding/rendering a list of items.
It has one child component `SearchBar` which holds a string. I use this string to filter the items shown to the user.

Ideally, I'd like to be able to query `SearchBar` and filter the list of items while rendering them, something like this:

```
render state =
    ul_ $
        renderBuildType <$> (filter (\bt -> bt.name == (query searchBar here)) state.buildTypes)
```

My current workaround is to hold two lists in `BuildTypesList`, one with all the items, and a subset of the first.

```
type BuildTypesState =
  { all         :: Array BuildType
  , filtered  :: Array BuildType
  }
```

This is kinda cumbersome because I have to manually enforce some invariants, e.g. update `filtered` whenever the user changes the text in the search bar (by peeking queries being passed to `SearchBar`), and whenever `all` is modified.

If I could query the search bar and filter the list on the fly (i.e. while rendering), I wouldn't have to worry about having to keep `all` and `filtered` in sync.

**Comment by natefaubion** [comment]
This is supported in `master`. Components have an input type, which is turned into a query that's dispatched at render time.

**Comment by dcastro** [comment]
Thanks @natefaubion. Where can I read more about this? Is there any documentation on the subject? I'm new to purescript-halogen and purescript in general, so I rely heavily on docs and examples.

**Comment by natefaubion** [comment]
I think the current (incomplete) docs in master are missing the section on parent/child stuff, but it's briefly mentioned in https://github.com/slamdata/purescript-halogen/blob/master/docs/2%20-%20Defining%20a%20component.md

The new component spec has a `receiver :: i -> Maybe (f Unit)` property (like `initializer` and `finalizer`). When you embed a component, you provide an input type of `i`. That `i` gets turned into a query via `receiver`. This is run on every render of the parent.

**Comment by natefaubion** [comment]
In that example, the input type is fixed to `Unit`, and the receiver is ignored via `const Nothing`, but you would just substitute a different type, and actually map it to a query.

**Comment by natefaubion** [comment]
I think I've misread your request, though. It is not possible to make an arbitrary query to a child and get a result back during rendering, because queries are asynchronous. In `master`, peeking is replaced by output messages. For this case, I'd recommend to either filter the list that way, or to flatten your component hierarchy. I'd ask myself if there was a need for `SearchBar` to be its own component, or if I could just embed it into the parent.

**Comment by garyb** [comment]
I think the `SearchBar` as a separate component can work fine too, it's just that instead of querying the from the list, instead you'd want to update a `filter` property in the list when the value in the search bar changes, that way you can filter during rendering with ` renderBuildType <$> (filter (\bt -> bt.name == state.filter) state.buildTypes)`.

**Comment by dcastro** [comment]
@natefaubion I'll try migrating to 1.0.0-rc.1 then. I'm guessing the changes you mentioned are all in the RC, right?

> you'd want to update a `filter` property in the list when the value in the search bar changes

Good point! I was worried about having two components keep track of that string (`SearchBar` and `BuildTypesList`), but on a second thought, the search bar doesn't have to keep track of the string in its state at all. It could just raise an event (i.e. `UpdateText String a`) that's meant to be peeked by parent components, and then just do `pure next` in its `eval` function.

Thanks all!
