### ISSUE TITLE
Toggling class attributes

### ISSUE THREAD

**Issue by themoritz** [slamdata/purescript-halogen#397]
I'm not sure if this is a halogen or halogen-vdom issue, so I'm posting it here. I've noticed that when I'm toggling the presence of a `class` attribute of a `div` that the classes that are present in the DOM aren't the same before and after toggling them on/off for the first time.

Take the following example, compiled with the current `master`: 

```purescript
module Main where

import Prelude
import Halogen as H
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HP
import Control.Monad.Aff (Aff)
import Control.Monad.Eff (Eff)
import Data.Maybe (Maybe(..))
import Halogen.Aff (awaitBody, runHalogenAff)
import Halogen.Aff.Effects (HalogenEffects)
import Halogen.VirtualDom.Driver (runUI)

data Query a = Toggle a
type State = Boolean

app :: H.Component HH.HTML Query Unit Void App
app = H.component
  { initialState: const false
  , render
  , eval
  , receiver: const Nothing
  }

render :: State -> H.ComponentHTML Query
render open = HH.div_
  [ HH.button
    [ HE.onClick $ HE.input_ Toggle ]
    [ HH.text "Toggle" ]
  , case open of
      true -> HH.div
        [ HP.class_ (H.ClassName "open") ]
        [ HH.div_
          [ HH.text "Open" ]
        ]
      false -> HH.div_ []
  ]

eval :: Query ~> H.ComponentDSL State Query Void App
eval = case _ of
  Toggle next -> do
    H.modify not
    pure next

type AppEffects = HalogenEffects ()
type App = Aff AppEffects
    
main :: Eff AppEffects Unit
main = runHalogenAff $ do
  body <- awaitBody
  runUI app unit body
```

When the app first renders, there is a `<div></div>` in the DOM. When I toggle to `true`, there is a `<div class="open"></div>`, as expected. But when I toggle again to `false`, I get `<div class="undefined"></div>`

In a larger project I've also had cases where the `open` class stays even though the state changes to `false`, but I couldn't reproduce it in this smaller example.

**Comment by garyb** [comment]
In the larger case, it may be because you don't have the latest `purescript-halogen-vdom`; a patch release was made to fix that, but it appears the "undefined" value is what happens instead now: https://github.com/slamdata/purescript-halogen-vdom/pull/12

I assume you are using the `VDom` driver and not `VirtualDOM` as you have in the imports there? :smile:

@natefaubion any ideas? Switch to using the attribute for `class`?

**Comment by natefaubion** [comment]
This is due to the way properties are "removed". It's not really possible to completely remove attributes when using their associated DOM properties. Halogen-vdom follows virtual-dom and sets removed properties to undefined. This has strange effects on some properties. One option is to just use attributes more within Halogen, so that things actually get removed with removeAttribute.

**Comment by themoritz** [comment]
Ah cool, the fix to halogen-vdom indeed solves the issue in my larger case. And yes, the `VirtualDOM` is only there because I wanted to see if there is still the old virtual-dom driver. :smile: 

I guess one can live with the "undefined" if one knows about it and never uses ".undefined" selectors hehe.

**Comment by natefaubion** [comment]
Obviously it needs to be fixed :). The conventional wisdom is that DOM props are faster than setAttribute, but I don't know if that's really the case anymore. We could customize prop removal as well, maybe.

**Comment by natefaubion** [comment]
The `v1.0.3` release of halogen-vdom removes string properties by setting it to the empty string (this is all that can really be done in the case of properties). To actually remove the attribute (like in the inspector), we'd have to use attributes.

**Comment by themoritz** [comment]
I'm totally fine with that!
