### ISSUE TITLE
Child components don't remember state when used in a certain way

### ISSUE THREAD

**Issue by potocpav** [slamdata/purescript-halogen#415]
I use child components to model pages (only one component is visible at a time). This is in the parent's `render`:
```haskell
HH.div_
    [ case page of
        Page1 -> HH.slot' CP.cp1 unit Page1.ui unit absurd
        Page2 -> HH.slot' CP.cp2 unit Page2.ui unit absurd
    ]
```
but when switching between the pages, the internal states of the components aren't preserved (they are re-initialized). 

Do I need to push all the state to the parent component, is there another way to do that, or is this a bug?

**Comment by cryogenian** [comment]
I think this is expected behaviour. I'd push state to the parent and propagate it through input message.

**Comment by garyb** [comment]
It's not a bug, this is the way things are supposed to work (otherwise Halogen would leak memory, as we have no other way of knowing when we can release the state associated with components).

There are 3 options you can use for this I think:

1. Do something to pull the state to the parent component before hiding a page / push when restoring, as you suggested.
2. Instead of changing the slots that are rendered in the HTML, wrap each in a container div and toggle the with `display: none` etc.
3. Have each page track its visibility status, and have them render nothing when their internal state says they should be hidden. The state could then be propagated via input message from the parent:
    ``` purescript
    HH.div_
      [ HH.slot' CP.cp1 unit Page1.ui (page == Page1) absurd
      , HH.slot' CP.cp2 unit Page2.ui (page == Page2) absurd
      ]
    ```

Option 3 is how I'd do it, personally.

**Comment by potocpav** [comment]
Thanks a lot for the reply! I will go with 3). This is probably a very common use-case, should it prehaps be mentioned in the new guide?

**Comment by garyb** [comment]
Yeah, I definitely would like to add some additional chapters explaining how to solve common problems, this'd be a good candidate for that. :)
