### ISSUE TITLE
Incorrect use of `widget`

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-halogen#42]
@natefaubion reports:

> `widgetImpl` always creates a new `Widget` class with unique `init` methods, which means that you’ll never get a call to `update`

**Comment by paf31** [comment]
I tried to get this working, but it's very difficult to see what's going on inside `virtual-dom`, and I haven't been able to figure it out yet.

I'm trying to follow this, but the diff doesn't seem to be working. It doesn't seem to recognize that two widgets are of the same type, and keeps trying to initialize the new version rather than update it. Maybe the `id` field is the key, but I'm not sure.

https://gist.github.com/Raynos/1bff2123314d1046fb07

If anyone who is familiar with `virtual-dom` can help, I'd really appreciate it. @garyb any ideas?

I'll try to wrap this up tomorrow.

**Comment by natefaubion** [comment]
I think I saw it here https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/update-widget.js

**Comment by garyb** [comment]
I think our `widget`/`widgetImp` needs to accept a `name` parameter (or generate one internally) that is set when instantiating a `Widget`, and then yes, they will be compared by `id` rather than `init`-function equality. So basically, for diffing, `name+id` is used, otherwise `init`.

The use of `key` may also help, but I'm not sure how that fits in with widgets.

**Comment by jdegoes** [comment]
Definitely a priority for us given our dependency on ace, echarts, etc.

**Comment by paf31** [comment]
I've updated the `widget` function:

- It now takes a `name` and an `id`
- It now returns a strongly-typed `Widget`
- It now has access to the driver function in the `Renderer`.

**Comment by garyb** [comment]
:+1:
