### ISSUE TITLE
Support webpack hot reloading

### ISSUE THREAD

**Issue by centromere** [slamdata/purescript-halogen#468]
Right now it doesn't seem possible to use webpack's hot reloading feature with halogen. This would be a welcome feature.

**Comment by safareli** [comment]
This example could only work when a component has one instance right?

Technically `lifecycleComponent` and others could be "🐒 -patched" as components are usually created statically, so you can have unique name for each component, but then you need a unique name for each instance too, which i think could be obtained by  🐒 patching of `slot`. 

It's not clear to me what should happen if you are registering subscriptions to some events on `initialize` for example or something like that.

**Comment by garyb** [comment]
It makes the assumption that all the components involved are "pure Halogen" too; which might well be the case most of the time, but if there's a component wrapping something like echarts, Ace, etc. then it won't necessarily be able to keep those in sync either, since the state for those things is not fully stored in the component state.

I'm hesitant to provide HMR support as part of the core Halogen library for those reasons - I think having a version that doesn't always work properly might be more offputting than saying that it's not natively supported since it can't be done for all cases in general.

If someone wants to make a project with this stuff in it I can link to it from the README though, with the disclaimer that it won't work for all possibilities.
