### ISSUE TITLE
Design Questions: parameters and type of initialState

### ISSUE THREAD

**Issue by maxsnew** [slamdata/purescript-halogen#473]
When I have a component that depends on some parameter based on its parent, say an initial size or url to talk to, there's 2 clear ways to do it:

1. Put the parameter into the internal state type.
2. Make my component a function `Param -> H.Component ...`

The 1st idea is bad from a design/documentation standpoint in that the parameter is a `Reader` effect, not a `State`.
The 2nd works fine, but introduces a redundancy in that the `initialState` field also takes some inputs and splitting the initial data into parameters and "startup state" leaks internal details so is less flexible.
I've been doing the 1st one, but now that I think it through it seems like the most modular way to do it is to just put all startup data into `Param` and have the initialState function take a `Unit` argument.

So my questions are twofold:

1. What is your preferred design?
2. Is there a point to initialState taking a parameter?

**Comment by natefaubion** [comment]
The "input" of a component is provided every time the parent is rendered. On initial mount of a component, the input is provided so that the initial state, and thus the initial render, can be derived from this initial input. Subsequent inputs are then issued as a query and the child can conditionally decide to transition it's internal state based on potentially new information from the parent. If you don't need to do this then I'd just use a parameter.
