### ISSUE TITLE
Reducing DOM diffing

### ISSUE THREAD

**Issue by Boscop** [slamdata/purescript-halogen#492]
Currently, whenever some little state data changes, the whole DOM is re-rendered and diffed, right?
Is someone working on trying to minimize that, such that only dynamic parts of the DOM are re-rendered and diffed (like in Glimmer.js or lit-HTML)?

**Comment by garyb** [comment]
The virtual dom diffing and DOM patching only occurs with the boundaries of a component in Halogen, so there's that. Virtual dom re-rendering can be reduced by having parts of the rendered content constant, so that only a minimal "path" of virtual DOM is rebuilt on state changes.

There aren't really any plans to further refine the way it works, and as far as I know nobody else is doing work towards it either. The rendering/driver situation is pluggable though, so in theory it's something that could be experimented with if someone had the inclination.

You would have to be rendering some pretty large documents at a good rate of FPS for diffing to become a serious overhead anyway I think :)

**Comment by justinwoo** [comment]
Worth noting that even in the React world, people are commonly windowing (limiting rendered items to what can be seen in the viewport) to get better performance out of rendering very large lists. One of my first PureScript demos was doing this: https://qiita.com/kimagure/items/92f0a278971c7deb8eb5, https://github.com/justinwoo/purescript-scroll-table (this uses an ancient version of Halogen though)
