### ISSUE TITLE
How to handle global state

### ISSUE THREAD

**Issue by sboehler** [slamdata/purescript-halogen#494]
Hi all,

I am coming from a React/Redux background and am in general quite satisfied with the idea of having both global application state (for data which is reused across compoents) and local component state (for handling forms, animation, etc). 

While halogen seems to handle local state very nicely, I have even after a lot of googling and reading issues and source code not really been able to find good guidance on how to implement a redux-like global state. While I've been able to convert the halogen 'interpret' example into [something quite useless that creates a global ref and writes to it as a response to local component actions by using a free monad (akin to redux action creators)](https://github.com/sboehler/purescript-halogen/blob/master/examples/global-state/src/Main.purs), it still eludes me how to come up with a way to re-render my component whenever the global state (or any subset of it) updates. One way I thought of was to locally interpret global messages / actions and use them to update local state, but my objective is to centralize the interpretation of actions and to just be able to evaluate the global state in the render function.

My intuition is telling me that the solution is probably in some way involving the EventSource API and the 'subscribe' facility, as well as passing the ref via reader monad into all components. However I am afraid I haven't been able to really connect the dots yet. Thus, I'd very much appreciate any guidance or even a small example on how to "connect" components with global state and how to react to changes accordingly. In general, from a beginner's point of view, it would be really helpful to have a redux-like global state example in the repository.

(As a side note, I've also looked into [purescript-pux](https://github.com/alexmingoia/purescript-pux), which handles global state quite nicely. However I am facing the opposite problem and am missing the ability to use local state. Form handling in particular strikes me as quite painful if only global state is available).

**Comment by felixSchl** [comment]
Sorry I don't have the technical answer to your question but I found myself wondering the same things a while back, really wanting to use halogen because it's developed and used by some of the smartest people in this space. Then i went to explore pux as well and came to the same realization. For now, found my sweet spot using purescript-react with purescript-react-spaces, purescript-react-redux and purescript-redux-saga. I'm also looking forward to the technical answer to your question :)

**Comment by rjregenold** [comment]
I was searching for the same thing and wrote a small book store app using Halogen and [Redox](https://github.com/coot/purescript-redox) to see if it would work. The code is not well documented and I am by no means an expert (or even good, really) at Purescript, but I managed to get it working and you are more than welcome to use any of these ideas.

I threw the repo up [here](https://github.com/rjregenold/purescript-book-store).

The DSL is defined in [Action.purs](https://github.com/rjregenold/purescript-book-store/blob/master/src/Action.purs).

The interpreter is defined in [Store.purs](https://github.com/rjregenold/purescript-book-store/blob/master/src/Store.purs).

I wired it all together in [Main.purs](https://github.com/rjregenold/purescript-book-store/blob/master/src/Main.purs).

I was trying to get the simplest thing possible working, so there is still a ton of room for improvement. For example, all my components bubble `ActionDSL` messages all the way up to the root component. This could probably be improved by using the `Reader` monad and putting the `Store` handle in there for components to use. I'm also not entirely sure how well the current way I have things laid out would scale to a medium or large app.

It has been about a month since I've looked at this, but I am more than happy to try and answer any questions you may have. Hope this helps.

**Comment by natefaubion** [comment]
> This could probably be improved by using the Reader monad and putting the Store handle in there for components to use. I'm also not entirely sure how well the current way I have things laid out would scale to a medium or large app.

This is essentially what SlamData does. Initial model is given to child component, and it subscribes to updates in it's initializer.

**Comment by natefaubion** [comment]
The SlamData Reader environment is `Wiring`, and the core store for the data graph is the `EvalWiring` (https://github.com/natefaubion/slamdata/blob/master/src/SlamData/Wiring.purs#L111-L121). Eval store handling: https://github.com/natefaubion/slamdata/tree/master/src/SlamData/Workspace/Eval. `Persistence` contains the core mutations, where `Card` and `Deck` are the graph nodes. Graph nodes have a corresponding `Bus` which components will subscribe to in their initializers.

**Comment by natefaubion** [comment]
Here is where a card component subscribes to updates: https://github.com/natefaubion/slamdata/blob/master/src/SlamData/Workspace/Card/Component.purs#L226-L227

**Comment by naglalakk** [comment]
Hi @natefaubion do I understand this correctly that all components that want to share a global state subscribe to the same parent? So Bus is the parent component, Card and Deck are the children of Bus so they can react to state changes from Bus?

**Comment by sboehler** [comment]
For the record (if anyone stumples upon this old question / thread), @thomashoneyman 's solution in https://github.com/thomashoneyman/purescript-halogen-realworld is spot-on and solves the issue of global state in a very generic way. Thank you!

**Comment by thomashoneyman** [comment]
For the record (part 2!), Real World Halogen no longer uses that solution, and instead uses a dedicated state management library for Halogen:
https://github.com/thomashoneyman/purescript-halogen-store

The core of it is here:
https://github.com/thomashoneyman/purescript-halogen-realworld/blob/main/src/Store.purs
