### ISSUE TITLE
Maybe it's better not to merge into master code, which is not published yet

### ISSUE THREAD

**Issue by kana-sama** [slamdata/purescript-halogen#539]
I have spent a lot of time trying to apply approach from the example with children based on rows and SProxy, because these examples are in master. `develop` branch seems good for this.

**Comment by cryogenian** [comment]
Dependencies usually provided using bower or psc-package using this approach you won't go into troubles with master/examples/readme :)

**Comment by thomashoneyman** [comment]
@kana-sama since all releases are tagged, `master` represents current development. the best thing to do is look at the same tag in the repository that you are using in your code.

For example, if you're on purescript 0.11.7, then you'd want to browse the repository at the 3.x tag:
https://github.com/slamdata/purescript-halogen/tree/v3.1.3

and then all the examples and docs will be up to date for your particular version.
