### ISSUE TITLE
Infinite re-rendering child components causes memory leak

### ISSUE THREAD

**Issue by acple** [slamdata/purescript-halogen#586]
I used halogen query for polling function, that was crashed by memory leak.

like this code:
```purescript
  render s =
    HH.div_
      [ HH.slot _child (s `mod` 3) child s absurd ]

  eval :: Query ~> H.HalogenM State Query Slot Void Aff
  eval = case _ of
    Increment next -> do
      modify_ (_ + 1)
      pure next

    -- simple recursion
    Loop next -> do
      liftAff $ delay (Milliseconds 30.0)
      eval <<< Loop <=< eval <<< Increment $ next
```
I using dispose/recreate lifecycle for child components.
Loop query was triggered by initializer, or HalogenIO.query on main.
GoogleChrome memory profiler indicates leaking memory.
This only occured when including re-rendering child components, as far as i know.

here is minimal repro project. can compile and includes some another pattern.
https://github.com/acple/purescript-halogen-memoryleak-repro
I tried:

* simple recursion on Query
* use MonadRec forever on Query
* call Increment query on main
* use Coroutine on main

all are same problem.

and, This is a question, is this wrong usage for Halogen? how to implement Infinite Timer-like function on component correctly?

---
Env:

* Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* purs v0.12.1
* purescript-halogen (on master, e51eee0afd4f9816a64242f9c4a7b67ffc157e7b)

**Comment by acple** [comment]
1 is good solution! but i want to do both single call and loop call, want to avoid duplicate codebase if can.
2 is correct in this repro project. but my original one has multiple slot and do add, update, dispose, and sort. polling and update automatically is caused out of memory.

**Comment by acple** [comment]
ohh, sorry I tried 1st solution now but still leak memory.
I understand that modifying state causes re-rendering so repeat it in single eval will be leak same as others.

**Comment by acple** [comment]
I personally investigated this issue, I found this is JavaScript's closure memoryleak problem caused by `Halogen.Aff.Driver.runUI`'s `render` and `renderChild`.
`handlerRef` in `DriverState` captures previous DriverState recursively.

details:
https://github.com/slamdata/purescript-halogen/blob/8b7ca52cc19de4d6f591a5ce87b03473efa57e7b/src/Halogen/Aff/Driver.purs#L181-L251

First, in `render`, handler(L193), childHandler(L195) and do block(L210) creates local function, that references and shares current DriverState ds(L186). handler(L193) will be stored in child's DriverState(L242), so ds cannot release.

Second, in `renderChild`, previous childrenIn(L230) is captured by case statement(L231), the capture-context will be shared with local function(L242), and stored in child's DriverState.

(this blog was very helpful. https://blog.meteor.com/an-interesting-kind-of-javascript-memory-leak-8b47d2e7f156)

---

I created a patch https://github.com/acple/purescript-halogen/commit/cb4f76f0b1c483b39302f7bbe3ab42c7db4d9fef, this will no longer increase memory usage. (without another memoryleak, see below)
But this is verrrry ugly workaround. I suppose this should not be merged master.
I believe this is compiler issue. Unnecessary capturing should be avoided as much as possible.

---

another memoryleak:
In `purescript-free`, Long-running DSL(contains Halogen Query) will causes `List` leak due to `purescript-catenable-lists`. this is already fixed and PR-ed. (https://github.com/purescript/purescript-catenable-lists/pull/38)

I checked at the title's repro project applied these patches does not increase memory usage.

**Comment by natefaubion** [comment]
Thanks @acple. I had made https://github.com/purescript/purescript/issues/3448 several months ago, and I knew it would cause trouble at some point.

**Comment by kirill-gavrilyuk** [comment]
This issue is pretty serious, as it can lead to **insane memory leaks**.

@acple have provided neat examples, let me provide extra few. 

---
### Root of issue:

Let me explain the root of this issue by JS example:



- This one causes memory leak: 

```javascript

var loop = function ( state ) {

    var _ = ( function fn1() {
        return state.smth;
    } )();

    var handler = function fn2( _ ) { 
    	return null;
	};

    var trash = state.trash.map( function fn3( a ) {
        return a;
    } );

    return setTimeout( loop, 100, {
        ...state,
        trash: trash,
        handler: handler
    } );
};

loop( {
    trash: Array.from( new Array( 1000000 ), function ( _ ) { return 0; } ),
    handler: function ( _ ) { return null; },
    smth: null
} );
```

- No memory leak, GC does well:

```javascript

var loop = function ( state ) {
	/*
    var _ = ( function fn1() {
        return state.smth;
    } )();
	*/
    var handler = function fn2( _ ) { 
    	return null;
	};

    var trash = state.trash.map( function fn3( a ) {
        return a;
    } );

    return setTimeout( loop, 100, {
        ...state,
        trash: trash,
        handler: handler
    } );
};

loop( {
    trash: Array.from( new Array( 1000000 ), function ( _ ) { return 0; } ),
    handler: function ( _ ) { return null; },
    smth: null
} );
```

---

Let's call functions created in the same lexical env as sibling-functions.

So, `fn1`, `fn2`, `fn3` are siblings. 

All siblings share the **same environment**.

In or case 
- `f1` access `state`
- `f2` access Nothing
- `f3` access Nothing 

But, as they share environment, `f2` referencing `state` because `f1` referenced it.

So, when we put `handler` into next `state`, we got the new state reference the old one via `handler`'s closure 

---

The solution in this case is either get rid of `f1` wrapper, or make `f1` not to reference all the previous state.

```javascript 
//...
    var _ = state.smth;
//...
```

Or


```javascript 
//...
	var state_smth = state.smth;
    var _ = ( function fn1() {
        return state_smth;
    } )();
//...
```

---

### Halogen memory leak:


Code from `halogen v5.0.0-rc.4`

```purescript
	-- ...
    let
      handler :: Input act -> Aff Unit
      handler = Eval.queueOrRun ds.pendingHandlers <<< void <<< Eval.evalF render ds.selfRef
      childHandler :: act -> Aff Unit
      childHandler = Eval.queueOrRun ds.pendingQueries <<< handler <<< Input.Action
    rendering <-
      renderSpec.render
        (handleAff <<< handler)
        (renderChild lchs childHandler ds.childrenIn ds.childrenOut)
        (ds.component.render ds.state)
        ds.rendering
	-- ...
    flip Ref.modify_ ds.selfRef $ mapDriverState \ds' ->
      ds' { rendering = Just rendering, children = children }
    -- ...
```

Gets compiled to ( except I have added some names to anonymous functions )

```javascript
//...
var handler = (function fn1() {
    var $94 = Halogen_Aff_Driver_Eval.queueOrRun(v.pendingHandlers);
    var $95 = Data_Functor["void"](Effect_Aff.functorAff);
    var $96 = Halogen_Aff_Driver_Eval.evalF(render)(v.selfRef);
    return function ($97) {
        return $94($95($96($97)));
    };
})();
var childHandler = (function fn2() {
    var $98 = Halogen_Aff_Driver_Eval.queueOrRun(v.pendingQueries);
    return function f3($99) {
        return $98(handler(Halogen_Query_Input.Action.create($99)));
    };
})();
var v2 = renderSpec.render(function ($100) {
    return handleAff(handler($100));
})(renderChild(lchs)(childHandler)(v.childrenIn)(v.childrenOut))(v.component.render(v.state))(v.rendering)();
//...
Data_Function.flip(Effect_Ref.modify_)(v.selfRef)(Halogen_Aff_Driver_State.mapDriverState(function (ds$prime) {
    return {
		...
        pendingHandlers: ds$prime.pendingHandlers,
        rendering: new Data_Maybe.Just(v2), // <-- BANG
        fresh: ds$prime.fresh,
		...
    };
}))();

//...
```

Note, that `f1`, `f2`, and `f3` ( as it references handler ) reference `v`, which is actually driver state. Say more: **all functions created into this lexical env. will reference driverState via closure** if at least one of sibling-function reference driverState in it's body.

Now, to get the memory leak we have to put one of this functions into new driverState, directly or not.

I do not know how exactly childHandler ( which references driverState via handler ) gets into `rendering` but it is: I have inspected it and found reference to childHandler into [[Scopes]]. Then we put `rendering` into new driverState.


So, this leads to something like a list, where new driverState indirectly references old driverState, so old one can not be collected.

---

### Fix ( bad and dirty ):

Actually, @acple have provided similar fix earlier. It will also do the trick. But it had one serious issue: NIH, u know :)

---

I have a huge state, which holds reference to HTMLMediaElement for some reasons, and I have to query components pretty often. All this leads to tab crash after few minutes of work, as it consumes 1G+ of memory. 

I made a temoporary fix for personal usage, as in my case I can not just ignore it.

```patch
--- a/src/Halogen/Aff/Driver.purs
+++ b/src/Halogen/Aff/Driver.purs
@@ -190,10 +190,16 @@ runUI renderSpec component i = do
     Ref.write Slot.empty ds.childrenOut
     Ref.write ds.children ds.childrenIn
     let
+      ds_pendingHandlers = identity ds.pendingHandlers
+      ds_pendingQueries  = identity ds.pendingQueries
+      ds_selfRef         = identity ds.selfRef
+
       handler :: Input act -> Aff Unit
-      handler = Eval.queueOrRun ds.pendingHandlers <<< void <<< Eval.evalF render ds.selfRef
+      handler = Eval.queueOrRun ds_pendingHandlers <<< void <<< Eval.evalF render ds_selfRef
+
       childHandler :: act -> Aff Unit
-      childHandler = Eval.queueOrRun ds.pendingQueries <<< handler <<< Input.Action
+      childHandler = Eval.queueOrRun ds_pendingQueries <<< handler <<< Input.Action
+
     rendering <-
       renderSpec.render
         (handleAff <<< handler)
```
Note `identity` here is to prevent accessors inlining back.

After applying patch compiled JS looks like:

```javascript
var ds_selfRef = Control_Category.identity(Control_Category.categoryFn)(v.selfRef);
var ds_pendingQueries = Control_Category.identity(Control_Category.categoryFn)(v.pendingQueries);
var ds_pendingHandlers = Control_Category.identity(Control_Category.categoryFn)(v.pendingHandlers);
var handler = (function () {
    var $94 = Halogen_Aff_Driver_Eval.queueOrRun(ds_pendingHandlers);
    var $95 = Data_Functor["void"](Effect_Aff.functorAff);
    var $96 = Halogen_Aff_Driver_Eval.evalF(render)(ds_selfRef);
    return function ($97) {
        return $94($95($96($97)));
    };
})();
var childHandler = (function () {
    var $98 = Halogen_Aff_Driver_Eval.queueOrRun(ds_pendingQueries);
    return function ($99) {
        return $98(handler(Halogen_Query_Input.Action.create($99)));
    };
})();

```

It fixed the issue as expected. 

---

### PS:

I totally agree with @natefaubion that it is compiler issue at first, and ideally it should be fixed there. But, it would be great to fix it into Halogen code, as it looks much easyer than development of compiler fix, so can be provided much faster.

Also: is it possible not to inline accessors directly, but inline "accessors binds". Where binding should be performed at the very top scope, where structure ( record ) first appears?

like:

```javascript
var rec = {...};
var foo = fucntion (){
	var handler = rec.handler;
	return function () {
		return handler(rec.somedata );
	};
};
```

Transform to:


```javascript
var rec = {...};
var rec_handler = rec.handler;
var rec_somedata = rec.somedata;

var foo = function (){
	var handler = rec_handler;
	return function () {
		return handler( rec_somedata );
	};
};
```

This seems like a possible solution, for me.

Also, this likely will solve Nate's example:

```purescript
foo = case _ of { bar } -> \_ -> bar
```

Wich now compiles to:

```javascript 
var foo = function (v) {
    return function (v1) {
        return v.bar;
    };
};
```

With transform it will be like:

```javascript
var foo = function (v) {
    var v_bar = v.bar;
    return function (v1) {
        return v_bar;
    };
};
```
