### ISSUE TITLE
`raise` on initializer is triggered unexpected timing

### ISSUE THREAD

**Issue by acple** [slamdata/purescript-halogen#591]
on child component, call `raise` in initializer was delayed after initializer is completed.

```purescript
----------------------------------------------------------------

-- child component definition

type ChildState = Unit
data ChildQuery a = Raise String a
type Output = String

child :: forall m. MonadEffect m => H.Component HH.HTML ChildQuery Unit Output m
child =
  H.component
    { initialState: identity
    , render
    , eval
    , receiver: const Nothing
    , initializer: Just (H.action (Raise "initializer")) -- use initializer
    , finalizer: Nothing
    }
  where

  render _ =
    HH.div_
      [ HH.p_ [ HH.text "this is child component" ]
      , HH.p_ [ HH.button [ HE.onClick (HE.input_ (Raise "button")) ] [ HH.text "BUTTON!" ] ]
      ]

  eval :: ChildQuery ~> H.HalogenM ChildState ChildQuery () Output m
  eval = case _ of
    Raise trigger next -> do -- called by both initializer and button click
      log $ "start " <> trigger
      raise "1 raise"
      log "2 log"
      raise "3 raise"
      log "4 log"
      raise "5 raise"
      log $ "end " <> trigger
      pure next

----------------------------------------------------------------

-- in parent component:

  render _ = HH.slot _child unit child unit (HE.input PrintLog)

  eval :: Query ~> H.HalogenM State Query Child Void m
  eval = case _ of
    PrintLog output next -> next <$ log output -- log here
```

console output:

```
// trigger by initializer, raise was delayed after complete initialization
start initializer
2 log
4 log
end initializer
1 raise
3 raise
5 raise

// trigger by button, this is expected behavior for me
start button
1 raise
2 log
3 raise
4 log
5 raise
end button
```

Is this by design or bug?
I think that difference in initializer and button event is very confusing and unintuitive.

repro code:
https://gist.github.com/acple/715d314ad253779ee1eaff83d8a6310b

---

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
purs 0.12.1
purescript-halogen (on master, e6ae854)

**Comment by garyb** [comment]
It's by design - there's a particular flow to the initialization process that delays queries and messages until a component is initialized, and it gets a little complicated when child components are involved too.

If you look at the `lifecycle` example, and check the console, it illustrates the initialization pattern.

I still haven't gotten around to writing the guide chapter on lifecycle unfortunately, but there are reasons for why the initialization order is the way it is - it's mainly ensuring that it is not possible to interact with an uninitialized component, as in prior versions of Halogen that was a thing that could happen, and it did not result in good behaviour.

**Comment by garyb** [comment]
As an explanation of what is going on here:

- initializers are run immediately after a component is rendered for the first time
- a child component must be rendered before it can appear in a parent component
- components buffers any queries that come in until the initializer has completed

So here, since the child component initializer is synchronous, the messages it is raising are being buffered on the parent component, since this is happening:

1. render child component
2. initialize child component
3. render parent component
4. initialize parent component

So the messages the child is raising are happening before the parent initializer even starts in this case.

**Comment by safareli** [comment]
So if you have a delay of 1000ms in initialize of child component, initialization of parent component will also be delayed by 1000ms?

**Comment by acple** [comment]
afaik, Yes you're right. Parent component's initializer will work after all child initializers are completed.
I'd written Affjax request in child initializer, parent's initial action was blocked until complete requests.
But we can use `H.fork` in child's initializer, finish child initializer immediately and run continuation asynchronously.

**Comment by garyb** [comment]
Yeah, I believe that's right. Running async things in an initializer is definitely better to be `fork`ed too 👍.

If you run an async thing in an initializer and don't fork it, it can make the UI appear broken/clunky as interacting with the component will also cause any queries that would be raised from even handlers to be buffered too.

That's a good reminder of another thing that is important to include in the lifecycle documentation. 🙂
