### ISSUE TITLE
Initialize in parent does not cause child component update

### ISSUE THREAD

**Issue by OndrejSlamecka** [slamdata/purescript-halogen#604]
I have a component with a child in a slot with input, the parent runs (slow) initialize which gets some data (intended to be the input to the child component), however, the child does not get updated with this data. Maybe I am using some feature wrong or maybe it's a bug? I am on halogen/v5.0.0-rc.4.

**How to reproduce:** I made https://github.com/OndrejSlamecka/reproduce-halogen-bug based on the `components` example and attempting to make the reproduction obvious with [this commit](https://github.com/OndrejSlamecka/reproduce-halogen-bug/commit/5c0e877ca92e004bed74ce3ad290afbbaf26aaa1). You can build the contents with 
`spago bundle-app -t dist/example.js` and open in a browser with `file:///.../dist/index.html`.

I then added a `spy` function in [the next commit](https://github.com/OndrejSlamecka/reproduce-halogen-bug/commit/6200dc354f3598b2668973fd5037dec3c5f182d7), showing "render slot", "render button", (wait for load), "render slot" but then no "render button" as I would hope.

**Comment by garyb** [comment]
1. `Initialize` runs after the component has been rendered for the first time, so the child component will first receive "not loaded".
2. A changing input value in a component is dealt with by a receiver. [In here](https://github.com/OndrejSlamecka/reproduce-halogen-bug/commit/5c0e877ca92e004bed74ce3ad290afbbaf26aaa1) you have added the plumbing for the value to be set on the child in init, but there's no `receiver` hooked up, so that's why it's not being updated after the 1s delay.

I'd also recommend that you `H.fork` the async action in the `Container` initializer, as until the initializer for a component completes all other queries, actions, and messages are queued - meaning it will appear on the page, but if the user tries to interact with it, nothing will happen during that async period, and then once it completes all the actions that occurred in the mean time will be triggered at once.

**Comment by garyb** [comment]
Take a look [at this example](https://github.com/slamdata/purescript-halogen/tree/master/examples/components-inputs/src) for child components that receive values from the parent.

**Comment by OndrejSlamecka** [comment]
Neat, thank you! I went with the naive way of converting my Halogen 4 code to 5 and hit the wall here.
