### ISSUE TITLE
Question: any design doc / history how halogen got design in terms of why a component needs Input, Message, Query etc.

### ISSUE THREAD

**Issue by haishengwu-okta** [slamdata/purescript-halogen#624]
A conversation originated from fp-purescript slack channel.

I'm studying examples from https://github.com/JordanMartinez/learn-halogen/tree/latestRelease/src/03-Parent-Child-Relationships/01-Childlike-Components
looks like there are two approach to update state of child from parent component
- send input (receive ->can trigger  handleAction hence update state)
- send query (handleQuery can update state)
Im curious what’s design purpose to have two approaches?

also are there any design doc / history how halogen got design in terms of why a component needs Input, Message, Query etc.

**Comment by haishengwu-okta** [comment]
from natefaubion

> The receiver is more of a continuous update, since it’s driven by the parent render. This gives you declarative “props” in React parlance. Queries are a discrete imperative invocation (like React instance refs).
Sometimes you want to inspect the state of a child, or have more control over when particular updates happen, but using queries for all synchronization lends itself to an extremely imperative style, and is error prone.

**Comment by haishengwu-okta** [comment]
Then I wonder 
- What are situations that people may need use Queries?
- Cant any situation be achieved by using Receiver & Message? e.g. if I need to read child-component state, I can send Input (receiver) and child could response a Message. Would that make the component interface simpler?

**Comment by garyb** [comment]
Here's a sort of history of how Halogen arrived at the way it is: https://discourse.purescript.org/t/questions-regarding-the-development-of-the-purescript-halogen-library/236/10

If you don't mind replicating the state of every child component in each parent component, then yep, you can use inputs and messages and ignore queries entirely.

If you're using components to encapsulate state, then inputs are best used for "continuous" values that affect the state of a component, whereas queries are "discrete" triggers, or for asking information from the component that is not revealed through outputs.

For an example, let's say we're going to make a collapsible panel component. We could have the parent be responsible for the state of it by providing a `Boolean` input as to whether it's open or not, and have it raise a message when clicked so that the parent can toggle it accordingly. Doing that means there's not much advantage in even having it as a component though, since it's just a chunk of rendering code pretty much. If we were to move the open/closed state inside the component, we could then take the input off it, and maybe the output too depending on what we wanted to do. Then, to allow it to be controlled by the parent still, we'd give it queries for toggling it open/closed, and perhaps to check the current open/closed state. This means the parent no longer needs to track the state of the panel, but if needs be can still get the information on demand, and can determine whether the panel should be opened or closed.

**Comment by haishengwu-okta** [comment]
Thank you @garyb !
