### ISSUE TITLE
Call javascript code as part of render

### ISSUE THREAD

**Issue by ssadler** [slamdata/purescript-halogen#629]
I might be missing something, but I didn't find a way to call javascript directly as part of the render process.

It seems like the Widget idea was at some point the solution for this, if you wanted to delegate control of some part of the DOM, but this is no longer the case? Or, the widgets have to be expressed in terms of `Prop` which has no escape hatch.

It would be really useful to have, for example, properties like "unsafeBeforeAttach" and "unsafeAfterAttach" with signature `Element -> Effect Unit`. Often the lifecycle of this code and the rendering goes together.

**Comment by safareli** [comment]
see [this](https://github.com/slamdata/purescript-ace-halogen/blob/32514ded5678743365745f16414dae102c84b24e/src/Ace/Halogen/Component.purs#L184-L185) and [this](https://github.com/slamdata/purescript-ace-halogen/blob/32514ded5678743365745f16414dae102c84b24e/src/Ace/Halogen/Component.purs#L195-L196)

**Comment by ssadler** [comment]
I'm aware of ref, I was but it's a bit unsightly as it makes part of the rendering "disjoint" in the sense that you have to trigger it separately and outside of the render function. The function to get a ref also returns Maybe, which is kind of awkward.

But I guess the point is, since the whole render process is functions mutating elements under the hood, what's the reason that there's no API to do that except via workarounds?

**Comment by garyb** [comment]
There's no direct mechanism to perform effects during rendering, no. It might be possible to do some stuff by dropping down into the `purescript-halogen-vdom` layer rather than stuff that Halogen provides itself, but I don't think even then there are hook-like mechanisms that you could rely on. Is that accurate @natefaubion?

Even if we were to include something that did allow effects during rendering it would be a bit weird, since it'd be constrained to `Effect`, as that's where `purescript-halogen-vdom` operates, rather than the `m` used for effects within a `Component` / Halogen app in general.

**Comment by garyb** [comment]
Re: `Widget`, they're just there as a general purpose extension to the VDom tree: https://github.com/slamdata/purescript-halogen-vdom/blob/34c032aa5f72b600d69ab970e2737ca533c6c118/src/Halogen/VDom/Types.purs#L26-L31

Halogen uses the `Widget` constructor for the component slot entries in the `VDom` tree and for thunking for memoized HTML subtrees: https://github.com/slamdata/purescript-halogen/blob/dd301747260620946956048a86e07e9efe1b6380/src/Halogen/Component.purs#L195-L197

These are then handled in Halogen's `VDom` driver: https://github.com/slamdata/purescript-halogen/blob/dd301747260620946956048a86e07e9efe1b6380/src/Halogen/VDom/Driver.purs#L73-L118

So the "widget" concept isn't specifically related to JS or anything, it's just a way of extending `VDom` with additional stuff that can be handled at render time. We'd need another widget type thing in the Halogen layer too to be able to leverage that in a `Component`'s `HTML`.

**Comment by natefaubion** [comment]
I think you would want to expose what Halogen uses internally for `ref`.
https://pursuit.purescript.org/packages/purescript-halogen-vdom/6.1.0/docs/Halogen.VDom.DOM.Prop#v:Ref

Halogen uses this to insert and remove named refs, but there's no reason it can't be evented.

https://github.com/slamdata/purescript-halogen/blob/dd301747260620946956048a86e07e9efe1b6380/src/Halogen/HTML/Properties.purs#L133-L137
https://github.com/slamdata/purescript-halogen/blob/7bb46c742c51b9cb32a6e798bf3e1336e4f3b463/src/Halogen/Query/Input.purs#L15-L17
https://github.com/slamdata/purescript-halogen/blob/ac67fd77053733d6745349b671a09db7b6a003fd/src/Halogen/Aff/Driver/Eval.purs#L52-L57

You just need an alternative to `ref` that uses the `Action` constructor instead of `RefUpdate`.

**Comment by ssadler** [comment]
Ah, so this CAN already be done :)

```haskell
import Prelude                                              
import Data.Maybe                                           
import Halogen.Query.Input (Input(..))                      
import Halogen.VDom.DOM.Prop (ElemRef)                      
import Web.DOM.Element (Element)                            
import Halogen.HTML.Properties as HP                        
import Halogen.HTML.Core as Core               
                                                            
manage :: forall r i. (ElemRef Element -> i) -> HP.IProp r i
manage act = HP.IProp $ Core.Ref $ Just <<< Action <<< act  
```

Then you can specify an action which will get run with `Created el`, `Destroyed el` etc.

**Comment by ssadler** [comment]
Thanks, I'll close this then.
