### ISSUE TITLE
Generate Events Revisted

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [slamdata/purescript-halogen#634]
I have looked at #98, #106, #114 and am unsure how to set the [HTMLElement.focus()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus) on an input.

It seems that `runUIWith` no longer exists and I am not sure how to indicate that there should be a post render function called.

It would be cool to have something like
```purescript
postRender :: HTML w i -> (Element -> m Unit) -> H.ComponentHTML action slots m
```

**Comment by garyb** [comment]
Modifying the state causes a re-render, so you can just perform the `focus` right after doing that in `eval`.

**Comment by BebeSparkelSparkel** [comment]
With `finalize`?

**Comment by garyb** [comment]
You can just do it anywhere in eval:

``` purescript
do
  -- currently showing original HTML
  H.modify_ ?something
  -- rerender will have occurred and you can `focus` here
```

In `HalogenM` every* `H.modify` will cause a re-render, and the next action you take in `HalogenM` will occur after rendering is complete.

\* caveat: if `modify` is given an `identity`-style no-op where the record is completely untouched, it will not re-render - the reason is a little convoluted, but basically there's a referential equality check done iin there. (Long version: `get` and `modify` are both implemented with the single `state` function in `MonadState`, without this check, using `get` would also cause re-rendering, which would be terrible for performance).

**Comment by BebeSparkelSparkel** [comment]
So I have to drop `mkEval` and make my own

**Comment by garyb** [comment]
By `eval` I mean whenever you're doing something in `HalogenM` - so if you have `handleAction` / `handleQuery` instead of a "custom" `eval` it also works in those.

**Comment by BebeSparkelSparkel** [comment]
Got it thanks!
