### ISSUE TITLE
Communication with JS loaded via CDN

### ISSUE THREAD

**Issue by deemp** [slamdata/purescript-halogen#801]
Hi! I don't quite understand how it's possible to use FFI with js loaded via CDN. It was mentioned [here](https://discourse.purescript.org/t/rfc-the-future-of-the-purescript-bundler/2844) that such thing happens rarely, but not how it's doable. 

> If you have any JS dependencies in your PureScript project, then you already must use a JS bundler like Webpack or esbuild (or take your FFI dependencies via a CDN, which is exceedingly uncommon).

Is this a bad practice? How is it doable?

**Comment by garyb** [comment]
I think the idea is you'd have FFI code in the project that assumes some object is available in `window` (or similar), rather than `import`ing the dependency directly in the FFI JS. So it's not really any different to usual in terms of the Halogen/PS side of things, it's if you have an external dependency that isn't included/directly referenced in the project bundle.

**Comment by br4ch1st0chr0n3** [comment]
Thank you for explanation, @garyb!
