### ISSUE TITLE
Reimplement Event monad in the style of ListT Par

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#90]
Why do we need this abstraction? `stopPropagation`, `preventDefault` etc can be implemented in `Event` monad. Interpreting of `EventHandler` is very slow (i.e. I've go a very ugly and sad lag when switch from 
```purescript
E.async $ Aff.makeAff $ \_ k -> do
      k $ M.SearchNextValue ch
      maybe (pure unit) Tm.clearTimeout search.timeout
      tim <- Tm.timeout Config.searchTimeout $ do
        E.runEvent (const $ pure unit) (const $ pure unit) $
          setQE (ch <> " path:\"" <> p <> "\"")
      k $ M.SearchTimeout tim
      k $ M.SearchValidation true
```
to 
```purescript
(pure $ M.SearchNextValue ch) `E.andThen` \_ -> do
  tim <- liftEff $ Tm.timeout Config.searchTimeout $ do
  E.runEvent (const $ pure unit) (const $ pure unit) $
    setQE (ch <> " path:\"" <> p <> "\"")
    (pure $ M.SearchTimeout tim) `E.andThen` \_ -> do
    pure $ M.SearchValidation true
```

I know that `EventHandler` doesn't depends on `Event` directly and can use any `Alternative` but what other `Alternative` can be used here?

**Comment by paf31** [comment]
I don't think `preventDefault` can be implemented using `Event`. How would you create an anchor element `<a>` which didn't cause navigation, or prevent the default operation in an `ondrop` event, for example?

I don't understand the question, because you don't seem to be using `EventHandler` in either example anyway.

**Comment by paf31** [comment]
@cryogenian Re: `Alternative`, you need to use `Event` since that's what `runUI` requires, but for other purposes, you could use, e.g. `Maybe`, or `List`.

Also, you might be able to tidy up some code by using rebindable do notation, with `(>>=) = andThen`. Just a thought.

**Comment by cryogenian** [comment]
Oh! I've mixed two unlinked questions, sorry. 
* First code sample works nice and fast. Second that uses `Event` works very slow. This is problem I think.
* We use effectful computation in `Event`, preventing default is effect. Why do we need to add additional abstraction layer over `Event (ListT (Aff e) _)`? 
```purescript 
-- preventDefaultEff is foreign function 
preventDefault :: forall e a fields. SomeEvent fields -> Event e a 
preventDefault ev = Event $ lift $ liftAff $ preventDefaultEff ev

foo = H.a [ E.onClick (\ev -> (preventDefault ev) `E.andThen` pure Signal) ] []
```

I mean if we have three layers **A**, **B** and **C**. **A** depends on **B** and **B** depends on **C**. **C** and **A** use concrete types, why do we need polymorphic in **B**? We can just remove those **B**.

**Comment by paf31** [comment]
/cc @jdegoes - my thoughts:

#### `Event` is slow

There is a bit more indirection in the implementation of `Event` - it uses `ListT`on top of `Aff` - and that's probably some of the reason for the slowdown.

I'm not a big fan of using `ListT` for `Event` because I feel like the interpretation is wrong from the user's point of view. `ListT` is about non-determinism, so using `ListT` is like saying "I'm going to try to generate an event by pruning an asynchronously-generated search tree and taking the first success", but that's not a great way to think about asynchronous code IMO. Point is, I'm in favor of changing the internals for another reason. I'd rather use something like `data Producer o m a = Done a | More m (Tuple o (Producer o m a))` with `type Event eff a = Producer a (Aff eff) Unit` which is the free monad transformer with a `yield `operation.

I don't expect this will improve the speed much over `ListT` honestly. Really, I'm not sure why it would much slower. Can we measure it?

#### `EventHandler` vs `Event`

I don't want to use `Event` to handle `preventDefault` for two reasons:

- I generally want to minimize the use of `Eff` inside `Event` for manipulating the DOM. It's not there for that, but we don't have a way of constraining the effects the user chooses to use. It's up to the user to limit the row of effects to only including things like `AJAX`.
- `preventDefault` has to be called synchronously, or it won't work.

**Comment by paf31** [comment]
I mocked up a version using a free monad transformer. It works and provides the same API, minus `andThen`, but some work is needed to integrate it into `Component`, since the kinds don't line up. I can spend some more time on it if we like.

Another option, if performance of `ListT (Aff eff)` is an issue, is to use `ContT Unit (Eff eff)` instead, or even `Parallel eff`, just for the performance-critical paths to get round the issue for now. Since you're using a timer anyway, it might be a good fit, since `ListT` will serialize all requests.

**Comment by cryogenian** [comment]
I don't think that `FreeT` can improve performance over `ListT` too. Maybe using `async <<< makeAff` is the option to use in performance critical parts. 

I see your point about `preventDefault` and `EventHandler`. But personally it seems a little strange for me to use wrapper of wrapper of wrapper to just preventing default behaviour.

**Comment by jdegoes** [comment]
On `Event`, I am writing a custom, optimized `AStream` for `Aff` which will utilize `Par` and not implement `Bind`. Asynchronous streams and variables are just too fundamental, so I need to make sure both have proper treatment in `Aff`, and I've already done variables with good results.

`Aff` *might* work for `preventDefault` (but is a bit messy as @paf31 says). Actions lifted using `liftEff` and not preceded by asynchronous actions are run immediately; that's part of the semantics of `Aff` and is not going to change. Need to think about it more, but just thought I'd throw that out there.

**Comment by paf31** [comment]
@cryogenian Is there a minimal example which I can compile, so that I can see the speed issue? Thanks.

**Comment by paf31** [comment]
@jdegoes This seems to be the only thing remaining in 0.5, but I'm still not sure what to do with it. I'm not sure I understand your approach with `Par`.

@cryogenian I think an small example would really help me to understand the speed issue, if you have one.

If speed is the issue, one option could be to use the representation of `Aff` (but allowing the callback to be called multiple times) under the hood, but with a `ListT`-like interface (with `uncons` etc.) so that the sequential structure is clear.

**Comment by jdegoes** [comment]
@paf31 Re: `Par`. Basically I want `ListT (Par eff)`, but faster than `ListT`, all bundled up into an `AStream eff` interface as part of `aff`. This will only provide `Applicative`, but with `<>` you can append streams, and possibly one could provide a monadic-like bind if necessary.

**Comment by paf31** [comment]
Got it. Presumably `Astream` would implement `MonadAff`, in which case, there's your monadic/sequential API.

**Comment by jdegoes** [comment]
Btw the instances I've seen of `andThen` could easily be done using `<>` instead. Honestly I can't think of any case where one would want the parameter of `andThen` (last element emitted?), except for those cases in which one wants non-determinism.

**Comment by cryogenian** [comment]
Sorry for delay. I've tried to reproduce it and found that issue is that in second sample is that `setQE` is blocking (it modifies location hash). In case of setting hash without `timeout` it works slow in first sample too. 

Thank you very much, I think it can be closed because I can't found any issues in other handlers.
