### ISSUE TITLE
Generate events

### ISSUE THREAD

**Issue by cryogenian** [slamdata/purescript-halogen#98]
How do you think is it possible to add pseudoattributes for `HTML` like `clicked`, `focused` etc? And if it setted to `true` generate an event. Can be helpful to change focus or select texts.

**Comment by paf31** [comment]
It should be fairly simple to implement these in terms of `init`, no?

**Comment by cryogenian** [comment]
Erm... Could you give a clue how to do it?

**Comment by paf31** [comment]
Something like

```purescript
H.div [ A.init if shouldClick then yield ThingToDoOnClick else empty ] []
```

?

**Comment by cryogenian** [comment]
Do you mean `initializer`? I can't find `A.init`

**Comment by paf31** [comment]
Yes, sorry.

**Comment by cryogenian** [comment]
I mean not to do something that we do when events are fired, but to fire those events. In example `e.focus()` or `e.select()`. I'm afraid it can be done only by `Widget`'s `init` not `A.initializer`.

**Comment by paf31** [comment]
Sorry, I was thinking of the jQuery-style, where `el.click()` means "generate a click event", and assumed you just wanted to generate the input to the state machine without a click from the user. Maybe we do need #89 after all...

**Comment by paf31** [comment]
Can we do this with hooks?

**Comment by paf31** [comment]
@jdegoes @cryogenian I've put an (untested) sketch of a possible solution on the `hooks` branch. I think we can use this to define custom attributes like `focus`. I don't have time to work on this any more tonight, but I can take a look tomorrow if this approach looks ok.

**Comment by paf31** [comment]
Here's a thought. What if you used a data attribute, and we did an effectful pass over the DOM after each render, to apply any custom attributes, using jQuery or `simple-dom`? I could add a hook to `runUI`, and it would probably be cleaner than hook attributes.

**Comment by garyb** [comment]
That might be an option, but manipulating the DOM outside of virtual dom can really be asking for trouble when you're not doing it with hooks, widgets, etc. Or is that what you meant by using the data attribute? Use that as a marker for "make change here"?

**Comment by paf31** [comment]
> Or is that what you meant by using the data attribute? 

Pretty much. The case I was thinking of was focussing a text box. We could set a `data-should-focus` attribute, and then use jQuery to focus or blur that element if necessary after rendering.

We could do the same thing with a hook in an attribute, defining

```purescript
focussed :: Boolean -> Attr
focussed = attr "halogen-hook-focussed" <<< makeFocusHook

makeFocusHook :: Boolean -> Hook
makeFocusHook = hook ...
```

I have a sketch of the second approach in the `hooks2` branch.

**Comment by garyb** [comment]
Sounds reasonable to me.

That general method is pretty much how I proposed widget initialisation should work in one of the many other discussions - although with the machinery hidden somehow. The idea being then we can delay init until the node exists, has size, etc.

**Comment by paf31** [comment]
> That general method is pretty much how I proposed

Sorry, which one?

Implementing widgets with the data-attribute approach seems possible, and even preferable, if we can cram arbitrary data into a data-attribute using `virtual-dom`.

**Comment by garyb** [comment]
Well it's something I did in a JS project, so it might not translate directly, but the idea was using a hook that registered a "update me" request on `hook`, and then after render those requests were all processed. The registration part in that case was done with a global array, so that wouldn't quite be the way to handle it, but perhaps a data-attribute could be used to similar effect.

In my case it was for triggering animations on elements rather than doing anything widgety, but it seemed potentially workable?

**Comment by jdegoes** [comment]
> The case I was thinking of was focussing a text box. We could set a data-should-focus attribute, and then use jQuery to focus or blur that element if necessary after rendering.

Note that this is really a symptom of the more general information flow problem I've been ranting about: which is that it's not possible to emit messages from an SF; rather, the SF can only emit stateless, declarative HTML, which is leading to questionable hacks like this (not that I have a good way of solving it, just remarking on why this issue is arising and why information is being forced through pseudo-attributes -- because that's the only way to get event-oriented information out).

**Comment by paf31** [comment]
> Note that this is really a symptom of the more general information flow problem I've been ranting about:

It seems what you're referring to is really a limitation of `virtual-dom`, or even React, or just the general "generate a pure virtual DOM element and patch" approach, unless I'm missing something.

Anyway, I want to nail this down so that I can implement something this weekend. Given everyone's current experience, which do we prefer?

- Support for hook-valued attributes
- Data attributes and support for custom post-render hooks

There's no reason we can't support both of course, but I think it would be good to pick one and stick with it. I prefer the second, since I think it actually subsumes the current widget implementation, and it is closer in spirit to the "push effects to the boundary" approach.

**Comment by jdegoes** [comment]
> It seems what you're referring to is really a limitation of virtual-dom, or even React, or just the general "generate a pure virtual DOM element and patch" approach, unless I'm missing something.

Yeah, ultimately I think we need a PureScript vdom that is built on something more expressive than vdom but less expressive and more constrained than `Eff DOM Unit` -- whatever it is, it should allow native widgets without onerous or unrealistic requirements (i.e. widgets and vdom would both 'compile' down to this common abstraction).

But I did want to point out that pseudo-attributes are a hack around information flow problems present in vdom, i.e. they are a way of emitting external messages (as opposed to declarative HTML). Iin JS you just mutate everything everywhere so these sorts of issues are less apparent.

> Anyway, I want to nail this down so that I can implement something this weekend. Given everyone's current experience, which do we prefer?

I defer to @garyb, @cryogenian, and @puffnfresh, as they're the ones who have to use this. :smile:

**Comment by garyb** [comment]
Custom post-render hooks seem like they'll be more useful given the requirements of widgets and Bootstrap-style functionality decorators, so my vote goes to the data attribute approach too.

Something to keep in mind is we need to preserve those when manually setting values via `dataSet`.

**Comment by paf31** [comment]
I think this is handled by #106, shall I close?
